### ISSUE TITLE
Faucet down?

### ISSUE THREAD

**Issue by MarkCWirt** [kovan-testnet/faucet#10]
Requested ether to address 0x00b9e694b6268f4Db5A8E29c0FdC4D169C98e98A via a gist. Request was accepted (and will not allow me to resubmit owing to rate limit), but the ether hasn't shown up in about an hour, and isn't on the chain.

URL used was:

`curl http://github-faucet.kovan.network/url --data "address=https://gist.github.com/MarkCWirt/ba593e4c4aed493f82001ecb054a13e1"`

**Comment by ddorgan** [comment]
Seemed to work fine now:

$ sh test-kovan-github.sh 
Kovan Ether on its way in transaction https://kovan.etherscan.io/tx/0xebddef592934224c815eb32aec18925df4a36cc9a6df02edfd1374340805deb6

Can you send on the transaction id?

**Comment by MarkCWirt** [comment]
I didn't capture it at the time, but it looks like it eventually went through. I see an ether at Transaction  0x100f3d8891dc3cde5be65f5b349f7393e95c94723085027304539c6a32bde8ad
that came though a few days ago.

I'll close the ticket.
