### ISSUE TITLE
Requesting 50 KETH for Defi Development

### ISSUE THREAD

**Issue by liqingnz** [kovan-testnet/faucet#100]
Hi, I am working on a new defi dapp. KETH is required for testing minting DAI from Maker and other usages from other platforms.

Here is my address: 0xe2d50CFb680ffD3E39a187ae8C22B4f81b092A10

Thanks in advance

**Comment by ddorgan** [comment]
sent: 0xe60660d4515c97b4170640ed657e189d6ac39c5a4699607b803621485973509a
