### ISSUE TITLE
Requesting 100 KETH for a new DeFi Protocol

### ISSUE THREAD

**Issue by aparnakr** [kovan-testnet/faucet#101]
I'm currently building a new options protocol for DeFi. As part of that I need a large amount of KETH to 1. Mint Dai (that will be protected by the options), 2. Mint the options (options need to be overcollateralized with ETH), 3. Create a uniswap pool for the options to be able to sell and buy them. 
My address is 0x61f6c99C42d1e823852d4f82057A8B77fbD08D48

**Comment by ddorgan** [comment]
sent: 0xf2180f79b3111eaea5aa07519deb3038f5bd6141c0e9a5fbd4ae069118fe28ba
