### ISSUE TITLE
request 20 keth to develop dai app

### ISSUE THREAD

**Issue by windtalker666666** [kovan-testnet/faucet#102]
i am a develop of an exchange ,recently need to use dai , 1.use Multi Collateral Dai ;2.need to use kovan test net ; pls help,and  my kovan test net address is : 0x58a7E5C770D4188C5c5d6A19e4bf8f67086d618f

**Comment by ddorgan** [comment]
sent: 0x98e1c988ea7ce8b00c612b51c5fbb41e26fd574c5b1bc655f6f76fbbe8330cd8
