### ISSUE TITLE
requesting 20 KETH for DAI app

### ISSUE THREAD

**Issue by wohamid** [kovan-testnet/faucet#103]
requesting 20 KETH to develop/test subscription service for DAI app. 

Address is: 0xDC11F673262f3Df7Ccf947D38f20BAFbf853Afd2

**Comment by ddorgan** [comment]
Sent: https://kovan.etherscan.io/tx/0x0d205b515e573490a1ca28a602daada16706a10f8235e984b7bf6dba64447263

**Comment by nguyenhuuminhkhai** [comment]
requesting KETH
0x7477b0c219FB286329F8BEb94738a899E5c53413
