### ISSUE TITLE
Requesting 10 KETH

### ISSUE THREAD

**Issue by ghost** [kovan-testnet/faucet#104]
Hi there,
we have changed the developer team a few months ago and ran into missing GAS supply since October. Due to the reason I'm not a coder I just realized a few days ago that many tx are not transacted correctly due to missing GAS. So actually we have hundreds (maybe thousands) of tx on https://kovan.etherscan.io/txs?a=0x4310d288698b7d2fe8a446074426886c3b3d1227&f=2
that need to be re-processed I guess. To avoid asking for 1 KETH every 24 hours I would be pleased to receive a larger amount so our Kovan-account is able to process the tx's.
Thanks Andi

**Comment by ghost** [comment]
Ah, I forgot the wallet address:
0x33809A7684c4F77fa20eFa22C66da5cc329F38c9
😆

**Comment by igorbarinov** [comment]
Sorry for the delay here are 100 KETH
https://kovan.etherscan.io/tx/0x93ab1e271da493d4a506004eb1315f22c89a4fd611e8cc465b420b379d1943ff
