### ISSUE TITLE
Requesting 200 kETH

### ISSUE THREAD

**Issue by EdNoepel** [kovan-testnet/faucet#105]
I work for the Maker Foundation.  We provide open-source tools to help the Ethereum community interact with the Dai Stablecoin System.  I'm seeking a large amount of kETH to help test these tools.

0xC140ce1be1c0edA2f06319d984c404251C59494e

Thanks in advance.

**Comment by igorbarinov** [comment]
Sorry for the delay 
Here is 1,000 KETH https://kovan.etherscan.io/tx/0x2b4ee526ec5190c0efb2d651adaa3b9986b1153cd7d97cf333aedae86c683fb5

**Comment by EdNoepel** [comment]
Much thanks, my friend.
