### ISSUE TITLE
Requesting 50 KETH for testing

### ISSUE THREAD

**Issue by champbronc2** [kovan-testnet/faucet#106]
I work for a cryptocurrency exchange, Rain.bh, and we need some KETH for our testing environment.

Could we get 50 KETH to 0x7db562c4dd465cc895761c56f83b6af0e32689ba?

**Comment by igorbarinov** [comment]
Sorry for the delay
here are 200 KETH
https://kovan.etherscan.io/tx/0x29e9d6fb9a3c3469d1ef7741f11b2f09bf702eb01bae1fab99b5e34a099a7fb1
