### ISSUE TITLE
Requesting 50 kETH for testing

### ISSUE THREAD

**Issue by Ruiub3i** [kovan-testnet/faucet#107]
We are a team of developers at @BetProtocol and we need this for around a 1 month of development with our third-parties using kovan.

Address : 0x746131E8aC4017E1223E7A223FC9fBc1638C5A1E

Thanks in advance

**Comment by igorbarinov** [comment]
Here is it 1,000 KETH
https://kovan.etherscan.io/tx/0xe5dc3b4ad2c2c76a4be1c1c37a1f04167146f25314df71885cf597860226beeb
