### ISSUE TITLE
I need 50 ETH for smart contract development.

### ISSUE THREAD

**Issue by zorancuc** [kovan-testnet/faucet#108]
I'm spending 0.8ETH for each smart contract deployment.

I need a lot of ETH to get my smart contract work.

0xea2f5C0E4aeB3c15367F73f2ecEe492086cC01cA

Thanks

**Comment by igorbarinov** [comment]
https://kovan.etherscan.io/tx/0x64140c1bccf8e4e4c2ddc2c2f9f6b6b87bc53d6a740e4721bc3cb6763f6eaaf2
