### ISSUE TITLE
Requesting 100 KETH for Project

### ISSUE THREAD

**Issue by apalepu23** [kovan-testnet/faucet#109]
Hey! I'm requesting 100 KETH for a new project that is under rapid development and testing. We roughly consume 1-2 KETH per round of fresh deployments, consume another 1-2 KETH for unit tests, and need another ~100 KETH for functional testing. 

Hope you accommodate the request, and if so, please send to 0xc5BE51ebf287fB233a61a9b9690815AcF18D064A

Thanks!

**Comment by igorbarinov** [comment]
I've sent you 10k KETH https://kovan.etherscan.io/tx/0x1af17d9def97a07cb2475d22a69b79a099bf157084a67c1f44aab07371f43655
