### ISSUE TITLE
Requesting KETH for coding bootcamp

### ISSUE THREAD

**Issue by awantoch** [kovan-testnet/faucet#110]
Hello! I am requesting ~100-250 KETH for a coding bootcamp. I'm a curriculum engineer for a FinTech/blockchain coding bootcamp and while we've been able to scrape by with using the Kovan faucet, it has bugged out on us on several occasions during pretty critical moments. As a temp solution, we split up the 1.5 KETH we got from the faucet among 60 or so students (we've got several iterations of the class about to start as well, so this number will be increasing rapidly), but of course this is not ideal since we already ran out. 😝 Alas, adoption must continue to spread!

The easiest solution for us is to store a larger amount of test KETH internally, and create our own student-facing faucet. The Kovan network has been a huge help, as it is much faster than Ropsten and allows for us to have more real-time activities. We leverage Ganache where we can, and someday might run our own PoA network, but having Kovan available as a live example has been fantastic, and we intend to be as conservative with using it as possible (only deploying "finished" projects and not cluttering the chain). 

The address we'd need the Ether at is `0xc3879B456DAA348a16B6524CBC558d2CC984722c` -- thank you so much for taking the time.

**Comment by igorbarinov** [comment]
Good luck with your class
Here is 10k KETH https://kovan.etherscan.io/tx/0xe44fed6fc6f3a31f94cb8db8ea052e4d3310eac92b90555701fe84a56034886a

**Comment by awantoch** [comment]
@igorbarinov thank you so much! Incredibly helpful!
