### ISSUE TITLE
Requesting 200 ETH for Enterprise fintech dev project

### ISSUE THREAD

**Issue by sarahwiley** [kovan-testnet/faucet#111]
We are developing an Enterprise-level fintech app that will be launched worldwide in the next couple months. We have done a lot of initial internal testing using small amounts of KETH from the various faucets, but are at the point in the dev process where we need larger amounts to expand our external test cycles and allow investors and reviewers early-access.

**Comment by sarahwiley** [comment]
please deposit to: 0xD57AE7B50ad8c5e96B1bc1882D81627f89a286eD

**Comment by igorbarinov** [comment]
https://kovan.etherscan.io/tx/0x64578ec273d31a5257d51f57f9a808c56957b2b0752723e36607d6ad3b07b7c2
sent 1000 KETH
