### ISSUE TITLE
Requesting lots of KETH for running unit tests against Kovan

### ISSUE THREAD

**Issue by mesozoic-technology** [kovan-testnet/faucet#112]
Hi there, I am building the Shell Protocol and want to run my tests against Kovan. 

Would be great to have a lot of KETH for that. If 1 KETH is 500 transactions, it would be great to have like 2000KETH. Or even more. Whatever you feel comfortable giving! 

https://cowri.io 

we are deploying very soon!

**Comment by mesozoic-technology** [comment]
Please deposit to: 0xA600AdF7CB8C750482a828712849ee026446aA66

Thanks!

**Comment by igorbarinov** [comment]
Sent 10k KETH
https://kovan.etherscan.io/tx/0xa8a3e37c45ca52e8dd430e6e6f8f4b05144d0238c6e336a6f2e21136d76806a9

**Comment by mesozoic-technology** [comment]
Thanks a lot Igor
