### ISSUE TITLE
Requesting 200 KETH

### ISSUE THREAD

**Issue by thebkr7** [kovan-testnet/faucet#113]
Howdy, We are testing our DEFI project and want to test with MakerDAO's DSR and with WETH integration. Therefore we will need to lock up actual eth to test and not just use it to pay gas. Send to this please. 0x16E48FF7AdaC492ca8f6b59fD5c89dfa54ba88f4

**Comment by igorbarinov** [comment]
https://kovan.etherscan.io/tx/0x3719a6fe5722630f63f6a094c9a1596e25cf6698bcaefec831e3a6bedff72651

sent you 200 KETH
