### ISSUE TITLE
Requesting 100 KETH for smart contract testing

### ISSUE THREAD

**Issue by haythamkhaled** [kovan-testnet/faucet#114]
I'm working on complex project and spend a lot of KETH for each deployment.

my address is 0xd4E83cB4b7776bF4A6D727c03555E12aE7330eE1

Thanks

**Comment by igorbarinov** [comment]
200 KETH on their way
https://kovan.etherscan.io/tx/0x1732b32b2bda5c099d70117b8a4a5fdfaa8d9cb6c9bc2bfbb82b46275d96c579
