### ISSUE TITLE
Request for 10K kEth (EthIndia Hackathon)

### ISSUE THREAD

**Issue by anubhavgirdhar** [kovan-testnet/faucet#115]
We are building on top of Compound on kovan Testnet and need Eth => Dai => cDai.
Since We need to show the LIVE interest earned through cDai in our dApp ( key feature ), We require big quantity of kEth.

Hoping for a quick reply.
Kindly Deposit to 0x277CC1637C6BaABBfD92656C09564D9B61d5B3BC

**Comment by igorbarinov** [comment]
Ok, I've sent it. Please don't forget to mention Kovan testnet in your submission.
https://kovan.etherscan.io/tx/0x5a0d6a9eb96f51a84090f8e9b3bb01820a691430e1cb2facacebcf2133694b4f

**Comment by anubhavgirdhar** [comment]
> Ok, I've sent it. Please don't forget to mention Kovan testnet in your submission.
> https://kovan.etherscan.io/tx/0x5a0d6a9eb96f51a84090f8e9b3bb01820a691430e1cb2facacebcf2133694b4f

Thankyou so much for the quick response! 
Expect a shoutout soon :)
