### ISSUE TITLE
500 kETH for a hackathon project

### ISSUE THREAD

**Issue by roheat** [kovan-testnet/faucet#116]
I am participating in ethindia hackathon and i want to deposit some funds into compound protocol to get a sustainable amount of interest for demo purposes.

If this request is approved. Please transfer KETH to 0x5222318905891Ae154c3FA5437830cAA86be5499 address.
Thanks!

**Comment by igorbarinov** [comment]
Sent 100 KETH
https://kovan.etherscan.io/tx/0x504b6d641309eee3b067b443f3093c56e824acec999269fe18930dfde5e8edbb
Let me know if you need more

**Comment by igorbarinov** [comment]
https://kovan.etherscan.io/tx/0x7f38355274dff3f0df22cbf8377088043adf8f670c335c2a04cc6f98211b5c96 
10k
