### ISSUE TITLE
KETH for testing purposes

### ISSUE THREAD

**Issue by en-mihail-vartanov** [kovan-testnet/faucet#117]
We are planning some testing for deposits/withdrawals on a crypto exchange platform
We would really appreciate if you could share a value of 50-100 KETH

Public address: 0x7dd6d521eb17ac6ea50118e86f31c712399eb433

**Comment by igorbarinov** [comment]
Here you go
100 KETH sent 
https://kovan.etherscan.io/tx/0x108c918e37a52b4ecc5725ccdc4a180fafa126944283b678474825f0f4dec9b9
