### ISSUE TITLE
KETH for Test Pruposes on Crypto System

### ISSUE THREAD

**Issue by matheusrmeloo** [kovan-testnet/faucet#118]
I work in a company that uses KETH for the tests and I can only get one KETH per day, being able to run only 3 tests a day, this is slowing down my work, could you provide 100KETH to this address: **0xBF959a8d22D7dBBa81B5182d53698916d07070d3** ?

**Comment by igorbarinov** [comment]
Here you go. 100 KETH sent 
https://kovan.etherscan.io/tx/0xece05f0c970df5dd72a551ff2034fa14516a3b8d505289d037d81681c54f4e0d

**Comment by matheusrmeloo** [comment]
Thankss for All man!!
