### ISSUE TITLE
Requesting KETH for dCZK stablecoin testnet

### ISSUE THREAD

**Issue by burningtree** [kovan-testnet/faucet#119]
Hello, we creating a CZK (Czech Crown) decentralized stablecoin as permission-less smart-contract.
We need lot of KETH for testing purposes, especially for minting Kovan DAI. Thanks

Project is live on Kovan Testnet here: https://testnet-dczk.gwei.cz/
Smart-contract is here: https://github.com/gweicz/dCZK/blob/master/contracts/DCZK.sol

Address: 0x971960f103d1098AF94Dc318D494BF6F472D8712

**Comment by igorbarinov** [comment]
how much KETH do you need?
how do you achieve stabilization of stable coin btw?

**Comment by burningtree** [comment]
@igorbarinov At least 100 KETH

It's about experimental fixed order-book stabilization + decentralized oracle (Chainlink, Tellor etc.). Same principle like WJPY - https://github.com/warashibe/WJPY

**Comment by igorbarinov** [comment]
Ok cool
I sent you 1000 KETH https://kovan.etherscan.io/tx/0xab4148cf7e12a663bbdef9d6e1e3a1593aafd0b4eda2a34633d9782fe67f665b

Good luck with the project
