### ISSUE TITLE
Requesting 200 KETH for ETHDenver

### ISSUE THREAD

**Issue by KevinVitale** [kovan-testnet/faucet#120]
Working on a hack project for ETHDenver. Would it be possible to get 200 KETH?
Address: 0x0Cbe55DF6ec0b2AD41274Dad7Ccf17fc632CF749

@igorbarinov 😬

**Comment by igorbarinov** [comment]
Good luck with the project
Sent 1k KETH https://kovan.etherscan.io/tx/0xcb45072a8e556ab0a8bab90d201a99e0987bc382446c4ff0cfd6824dc50357e1

**Comment by KevinVitale** [comment]
@igorbarinov thanks! Your help was invaluable to our project: https://github.com/KevinVitale/Kettle

**Comment by igorbarinov** [comment]
> @igorbarinov thanks! Your help was invaluable to our project: https://github.com/KevinVitale/Kettle

Cool. Congrats on the 1st prize!

**Comment by qjawe** [comment]
Working on a hack project for AAVE marketmake https://mm.ethglobal.co/ . Would it be possible to get 1000 KETH?
Address: 0x7B88DF8AF7a283e3dc84A7Fd97Fde19cAbb90eD4

@igorbarinov 😬
