### ISSUE TITLE
Requesting 100 KETH for ETHDenver 

### ISSUE THREAD

**Issue by 0xJayShen** [kovan-testnet/faucet#121]
I work for a blockchain company.There are many testing tasks. Would it be possible to get 1 00KETH?
Address: 0x9Ba9Ae032a2709efb6eB5651b78058F19f01A38C

@igorbarinov 😬

**Comment by igorbarinov** [comment]
Sure, here are 100 KETH
https://kovan.etherscan.io/tx/0xafa93faf2340c4455dc774fc3373d1ae11c2e34deef92ab341b64f4122c32697
