### ISSUE TITLE
Need keth: ETHDenver dapp development

### ISSUE THREAD

**Issue by junoware** [kovan-testnet/faucet#122]
Hi. I'm working on a dapp from ETHDenver.

Can you please deposit a thousand keth at the following address?
0x2C93d2Df11bD6B2BcFca265cadA30B457C28B15d

Thank you.

**Comment by igorbarinov** [comment]
Sent you 1000 KETH https://kovan.etherscan.io/tx/0x0603deea8854e014607604334e5bb0643ddac5af08e680ba0de49d2885817c6e
