### ISSUE TITLE
Requesting 100 KEth for testing

### ISSUE THREAD

**Issue by markspanbroek** [kovan-testnet/faucet#123]
I'm working on a couple of smart contracts for the [Sustainable Source](http://sustainablesource.io) project, and I want to switch from Ropsten to Kovan for testing. Could you send 100 KEth to 0xc995206c20d29A428cc8535279525086b6e15C48? That should be enough for about a year's worth of testing. Thanks!

**Comment by igorbarinov** [comment]
Cool. Here is a 1k of KETH for 10 years of testing https://kovan.etherscan.io/tx/0x831e398fdb90e73a9a0780141d6214868e74e77618cd81efe40fb4920f445469

**Comment by markspanbroek** [comment]
Awesome, thanks!
