### ISSUE TITLE
Request for KETH in decentralized app Testnet

### ISSUE THREAD

**Issue by algarecu** [kovan-testnet/faucet#124]
Hello, we have a decentralized app that uses Ethereum and Hyperledger, [geodb](https://github.com/devgeodb/geodb-dlt-core), and we are running out of KETH for our initial deployment in Kovan testnet. We are consuming around 5 KETH every 24 hours and we are about 3/4 months away from having to refrain from testing in testnet I would say. Could someone send us a convenient amount of KETH to our address? That would be very much appreciated and contribute to our efforts to decentralize the Big Data Market, thanks in advance.

Address for KETH:
`0xDCF7bAECE1802D21a8226C013f7be99dB5941bEa `

**Comment by igorbarinov** [comment]
Here is 500 KETH https://kovan.etherscan.io/tx/0x88a41ffc5f0943f35d6c6a0fdd9c7403649ccf3a89b49b9374d739128b3c465e
Good luck with the testnet
