### ISSUE TITLE
Requesting 1K KETH for DApp Development

### ISSUE THREAD

**Issue by shengda** [kovan-testnet/faucet#125]
Hi, we are now developing a DApp toolkit for DeFi developers, and we need 1K KETH for testing in Kovan. Thank you!

**Comment by shengda** [comment]
Our address is 0x2932516D9564CB799DDA2c16559caD5b8357a0D6

**Comment by igorbarinov** [comment]
@shengda here is 1k KETH https://kovan.etherscan.io/tx/0x7270628d87a7f98c765eac67b79de9df7f85d3dc663c7ddb6fcbf86bca80cc30

Please let us know what is the project you are talking about!
