### ISSUE TITLE
Request for KETH to deploy and testing the smart contracts

### ISSUE THREAD

**Issue by nanthanwa** [kovan-testnet/faucet#126]
I'm a student who is researching about producing pseudorandom numbers in Ethereum blockchain (on Kovan network).
I need some KETH to deploy smart contracts and testing.

My ETH address: 0x7cA8E61E25B850cF13f3a75Ef86024c03cf90bC6

Thanks

**Comment by igorbarinov** [comment]
Hey. Send 100 KETH to you
https://kovan.etherscan.io/tx/0x26931a046b482bc85117d6f008da1bac1bd370a770a83c1a6d69704413f7501d

Meanwhile, we have RANDAO activated on consensus layer on another POA Testnet (Sokol)
and have an app you can play with which is utilizing the randomness feature

Documentation on Randomness https://www.poa.network/for-developers/on-chain-random-numbers
POA Mania http://poa-mania.herokuapp.com/
POA Mania docs https://poa.gitbook.io/poa-mania/
Faucet to get test coins for POA testnet (Sokol) http://faucet.poa.network/

**Comment by nanthanwa** [comment]
@igorbarinov thanks for KETH and the information about RANDAO, I will try it. :)
