### ISSUE TITLE
Request for 500 KETH for Crypto trading platform testing

### ISSUE THREAD

**Issue by en-mihail-vartanov** [kovan-testnet/faucet#127]
Hi, we are now developing a Crypto trading platform. Could you please share 500 KETH to the below address:
0x0333a049bf2ed14a405e6b4e72360213bb56cb72

Thank You in advance!

**Comment by igorbarinov** [comment]
Sent 500 KETH https://kovan.etherscan.io/tx/0xada6201a52aeb4c829cd473a721be32a1d07afa8ea6ad4647140d62a182ac722

Good luck with your platform
