### ISSUE TITLE
Need more kovan to tests of my new blockchain

### ISSUE THREAD

**Issue by matheusrmeloo** [kovan-testnet/faucet#129]
I'm creating a blockchain and I need to test new features that depend on Kovan Faucet, each test spends 3 KETH, could you send me 100 KETH to do more tests? For this wallet:

0xBF959a8d22D7dBBa81B5182d53698916d07070d3

**Comment by igorbarinov** [comment]
Please create your request here https://forum.poa.network/c/kovan-testnet/faucet-requests/107
