### ISSUE TITLE
Require atleast 10 KEth to test and get my hands on makerDao.

### ISSUE THREAD

**Issue by surajsingla333** [kovan-testnet/faucet#130]
Hi, 
I am a blockchain developer and want to get my hands-on MakerDao and stable coins. 
This is my wallet address: (0xd27189917dd3E4B0e9eB731eCEe358254520FA01)
Requesting for atleast 10 KEth.

**Comment by ohmydefi** [comment]
same here
0x93c268D72568c82828DDa102fe57cc3A70ace878

**Comment by igorbarinov** [comment]
Please create your request here https://forum.poa.network/c/kovan-testnet/faucet-requests/107
