### ISSUE TITLE
Requesting 15 KETH

### ISSUE THREAD

**Issue by NathanielMNDZ** [kovan-testnet/faucet#131]
Hi - I am requesting 15 KETH to supply to 15 individual wallets to be used in testing of a DeFi platform that I am building @ here https://www.greenwood.app/

thanks and please let me know if more info is needed

0x874B3f4a65d850358d80215B09F67Eddd983D6B0

**Comment by igorbarinov** [comment]
Please create your request here https://forum.poa.network/c/kovan-testnet/faucet-requests/107
