### ISSUE TITLE
Require 2000 KETH for testing

### ISSUE THREAD

**Issue by nicoelzer** [kovan-testnet/faucet#134]
Hi, 

we are testing a soon to be launched protocol and need large amounts of ETH in order to imitate transactions.

Requestion 2000KETH to address 0x0500f8C8AAD954936b86c06AFBa5D4e27b806352

Thanks!

**Comment by igorbarinov** [comment]
Please create your request here https://forum.poa.network/c/kovan-testnet/faucet-requests/107
