### ISSUE TITLE
Require 2000 KETH for testing

### ISSUE THREAD

**Issue by ohmydefi** [kovan-testnet/faucet#135]
Hello, we were finalist at last ETHDenver with the [ohmydefi](https://ohmydefi.com)! project. 

And we are heavily testing flash loans and makerdao! 

Can you please give us 2000 KETH? to that address: 0x2367386801e28b15A7ef606fD55Fe455dfEE6053

Thank you!

**Comment by igorbarinov** [comment]
Please create your request here https://forum.poa.network/c/kovan-testnet/faucet-requests/107

**Comment by igorbarinov** [comment]
2k sent https://kovan.etherscan.io/tx/0x313448b76f6eccae06d26d4278ddaef7bf4e212ff2edaf068be42be50801b8cd
