### ISSUE TITLE
Requesting 2000 kETH

### ISSUE THREAD

**Issue by ghost** [kovan-testnet/faucet#138]
I work for the Maker Foundation. We provide open-source tools to help the Ethereum community interact with the Dai Stablecoin System. I'm seeking a large amount of kETH to help test these tools.

0x9E4564dE2D764a0B005Bcb5cD38D98A7Ac43BC0F

Thanks in advance.

**Comment by fairgogame** [comment]
@igorbarinov 😬

**Comment by fairgogame** [comment]
> I work for the Maker Foundation. We provide open-source tools to help the Ethereum community interact with the Dai Stablecoin System. I'm seeking a large amount of kETH to help test these tools.
> 
> 0x9E4564dE2D764a0B005Bcb5cD38D98A7Ac43BC0F
> 
> Thanks in advance.
