### ISSUE TITLE
Request 3000 KETH for automated testing

### ISSUE THREAD

**Issue by Ruiub3i** [kovan-testnet/faucet#139]
Hey,

We at betprotocol.com need around 3k for half a year worth of testing.

Send it here if possible : 0x4d488C78D6383A8C428413c3102AdF788a25Afb0

Thanks

**Comment by igorbarinov** [comment]
Please create your request here https://forum.poa.network/c/kovan-testnet/faucet-requests/107

**Comment by igorbarinov** [comment]
https://kovan.etherscan.io/tx/0xeb09884cd0de76c1caca404d1809690610397f545b72211755fa3ec6e5e927f8

3k sent
