### ISSUE TITLE
150 Keth needed for running experiments

### ISSUE THREAD

**Issue by bx3** [kovan-testnet/faucet#145]
Hello,

I am writing a codebase that aims to scale the throughput of Ethereum using sidechain type technology. I plan to run tests to evaluate the performance the code. Each run has 50 nodes and each individual submitting 100 transactions. I have three configurations and each needs at least 5 runs.

In total, I need to run 5 * 3 * 50 *100 transactions, which translates to roughly 150 Keth. Can you send to the following address?
0x97952767d3748FA35443c6319eA0ef192C5d1a76

Thanks much

**Comment by igorbarinov** [comment]
Please request here https://forum.poa.network/c/kovan-testnet/62
