### ISSUE TITLE
Parity SMS verify not working?

### ISSUE THREAD

**Issue by onpaws** [kovan-testnet/faucet#15]
Not yet another request for Keth -- a question.
Is the Parity SMS verify service supposed to be working?

I read the [instructions](https://github.com/kovan-testnet/faucet) which point to a [video tutorial](https://youtu.be/99UucFzYCRc).
So I carefully set up a local Parity instance, waited for it to sync, transferred real Eth as instructed by the Parity "verify" UI. 
However I haven't received an SMS.
Is the Twilio (or whatever SMS gateway) down?

**Comment by ddorgan** [comment]
This service has been retired.

**Comment by onpaws** [comment]
Thanks for posting back.
Are you aware of this retirement being handled on the Parity UI side?

Seems like it'd be great for the Parity UI to no longer set folks up for missed expectations.
