### ISSUE TITLE
502 Bad Gateway - https://faucet.kovan.network/

### ISSUE THREAD

**Issue by PtrckM** [kovan-testnet/faucet#159]
https://faucet.kovan.network/

![image](https://user-images.githubusercontent.com/54516858/101342221-3854fb80-38bd-11eb-9579-02bf4b74b900.png)

**Comment by NonnonGo** [comment]
Same issue

**Comment by mudgen** [comment]
I am also having this issue.

**Comment by mrjordan86** [comment]
I have it as well

**Comment by nmdshenoy** [comment]
same problem as on 10th dec 2020 @4.08 pm Indian Standard Tie

**Comment by NikMarin** [comment]
28 dec 2020, can't get kETH :(

**Comment by PtrckM** [comment]
its up and running again!!!
![image](https://user-images.githubusercontent.com/54516858/104449362-75598f80-55d9-11eb-875a-46ea4ad39308.png)

**Comment by ddorgan** [comment]
This was fixed a while back.
