### ISSUE TITLE
faucet not recognizing certified mainnet account

### ISSUE THREAD

**Issue by jacbop** [kovan-testnet/faucet#16]
I SMS certified my account yesterday:

![image](https://user-images.githubusercontent.com/4127225/39608350-7ab8f646-4f06-11e8-9e1a-47cf5d0b0199.png)

But I continue to get `Account not certified` when I visit the faucet.

![image](https://user-images.githubusercontent.com/4127225/39608373-a3c3b76a-4f06-11e8-859a-2894fc969bb2.png)

Is something down? Or am I doing something wrong?

**Comment by ddorgan** [comment]
Can you re-try please?

**Comment by Tbaut** [comment]
SMS certifier is now deprecated (not GDPR compliant)
