### ISSUE TITLE
faucet has been ignoring my requests for KETH

### ISSUE THREAD

**Issue by dkent600** [kovan-testnet/faucet#17]
When I go the gitter faucet (https://gitter.im/kovan-testnet/faucet) and request KETH, it ignores my requests, while responding to others'.  Doesn't matter what address I submit. 

Any idea what it going on?

**Comment by dkent600** [comment]
Additional info:  I tried logging in via twitter instead of GitHub and submitting a request for KETH.  This time I got a response (instead of silence), saying that I had "requested too recently, try again in 6 hours".

It appears to be finding the previous request that I made when logged-in via GitHub, reacting _as if_ the faucet had responded at that time by sending me KETH, when in fact it hadn't.

**Comment by avonian** [comment]
same here :\

**Comment by GILLIARDFN** [comment]
SEND 5 ETH 0x36f9a509d0dfb18d540fb97e100ec331d80da4a8

2018-06-04 21:35 GMT-03:00 avonian <notifications@github.com>:

**Comment by GILLIARDFN** [comment]
0x36F9A509D0dfB18D540Fb97E100ec331d80dA4a8

**Comment by ranjit12321** [comment]
the faucet ignoring my request

**Comment by ranjit12321** [comment]
the faucet ignoring my request
0x11b705Dec18192a306b7329C54C1e68c0e2e41d2

**Comment by dkent600** [comment]
Please note that this is not about the faucet occasionally taking a break, this is about my specific account having been ghosted.


In any case, today I find that I seem to have been unghosted, is working properly now (albeit with 3KETH instead of 5).

**Comment by ddorgan** [comment]
Can you please re-try now.

**Comment by dkent600** [comment]
@ddorgan A couple days ago I retried and it worked.  Then 26 hours later I found was ghosted again.

Seeing your message above, I tried again just now and find I am still ghosted.

**Comment by donaldduckcheshta** [comment]
gitter faucet is taking long to reply . I have been waiting from evening for KETH with no luck . My wallet address below 

0x007510BdDAF1144E4C6c29cD4bC3c0af0ea381a8
0x00A10bF2247556Ca1cDeBF8E66f9994f75A1419D

Request you to please assign KETH . My work is impacting .

Thanks

**Comment by donaldduckcheshta** [comment]
Or is there any other way to get test ethers on kovan . Kindly suggest .

Thanks

**Comment by dkent600** [comment]
Reason for closing?

**Comment by Tbaut** [comment]
Because the faucet is working (at least partially so that you should have had your kovan ether) and this issue was slowly spammed by addresses asking for Keth, which is not what an issue is made for :)

**Comment by dkent600** [comment]
Yes it does appear to be working for me now.

**Comment by ddorgan** [comment]
@dkent600 do you mean using the old sms faucet or the gitter faucet? 

BTW you can also now try: https://faucet.kovan.network

**Comment by dkent600** [comment]
@ddorgan I was referring to this:  https://gitter.im/kovan-testnet/faucet, which was the original subject of this issue.

Thanks for the link to the other one.

**Comment by ddorgan** [comment]
Ah ok thanks!

**Comment by sarah0504** [comment]
My request is also ignored, what i could make please?
