### ISSUE TITLE
Eth required for the deployment of a DAPP for testing purposes

### ISSUE THREAD

**Issue by sai1211sai** [kovan-testnet/faucet#171]
account address: 0xCAe66D2A339f84e334B8F8dc5B22ef73f6a96B92

**Comment by a122-2345** [comment]
0xC5088e48e36A7B74CaAc6396D26aFB56Be3C949a

**Comment by vincent-wang-ffk** [comment]
0x8065bF5FD32CbdAD0678d00784b62c717aaD336b
i need test dapp,thanks

**Comment by zirgudaga** [comment]
0xF5E275DDb9e6BaaB3AD1d867cD100f8Bedd2Af63

**Comment by KodockOne** [comment]
0x0e4B02eB5e8c4ddA7dE7E7555576BA672A98195C

**Comment by ddorgan** [comment]
Faucet is now working
