### ISSUE TITLE
FAUCET IGNORING MY REQUEST

### ISSUE THREAD

**Issue by ranjit12321** [kovan-testnet/faucet#18]
The faucet ignoring my request . and i didnt get anything.
" send 5 eth to 0x11b705Dec18192a306b7329C54C1e68c0e2e41d2"

**Comment by vngassam2018** [comment]
the KETH isnt recognised on eth main net on metamask

**Comment by ddorgan** [comment]
Can you please re-try now.

**Comment by ddorgan** [comment]
Closing.
