### ISSUE TITLE
It seems its no longer 5 Keth via the gitter faucet, now its 3

### ISSUE THREAD

**Issue by zachlysobey** [kovan-testnet/faucet#19]
I just wanted to verify this before opening a PR to update the docs here. But it seems like the rules have recently changed?

**Comment by Tbaut** [comment]
Yes it's true.

**Comment by zachlysobey** [comment]
@Tbaut do you know what the new rules *are* precisely? Are the documented somewhere? I’d be happy to open a PR here...
