### ISSUE TITLE
Request for 30 kETH or whatever you can spare

### ISSUE THREAD

**Issue by nodezy** [kovan-testnet/faucet#191]
hey guys i posted this on the POA forum but still don't have any takers...I really need to start testing today if someone could help, I don't need much kETH maybe 30 but I'll take whatever can be spared, thanks.

`Hi everyone! I am helping to deploy contracts for a token that was recently rugged and now community run. They want 1% RFI on buy/sells to go to charity, so in order to test these features I will need to create a small LP and test buys/sells on netlify.app to make sure all the fee-on-transfer stuff works properly.

The address is 0x6f99b403e1845817515A982b13b06d85Cf33B658 if you could spare 30 or so KETH that should be enough to create a pool for testing as well as any future projects I am involved in. Thank you so much!`

**Comment by ddorgan** [comment]
Faucet is now working
