### ISSUE TITLE
Koven Testnet Faucet is empty/not-working? 

### ISSUE THREAD

**Issue by anhtu98** [kovan-testnet/faucet#196]
I need some Kovan ETH to experience the service. Send me about 10 ETH. Thank you.
0x4a84439E700634a1Bc0a5646865CDD06b44BBd83

**Comment by ddorgan** [comment]
Faucet is now working

**Comment by vingit1** [comment]
send 10 ETH 0xf0820cd7e045D191BbF88dCFB736a68f21B202C3

**Comment by suchat932** [comment]
ไม่มีครับ
