### ISSUE TITLE
Need 0.5 kETH for INJ testing

### ISSUE THREAD

**Issue by zbtiqua** [kovan-testnet/faucet#216]
Hello,

Need a small amount of kovan eth (or PAXG) in order to swap for PAXG, so I can propose market listings on the current INJ testnet governance. Just need a small amount of kovan PAXG in the account at the end, as this is required for the testnet governance. Any assistance is appreciated.

**Comment by CHRISTINIMA** [comment]
Our development team now we need 20keth to test the settlement system
Please send to
0x5e50cBB482354ac81C2b01387a0e2F9120b49463
