### ISSUE TITLE
Kovan Faucet is taking long in responding from last 2 weeks

### ISSUE THREAD

**Issue by donaldduckcheshta** [kovan-testnet/faucet#23]
gitter faucet is taking long to reply . I have been waiting from evening for KETH with no luck . My wallet address below

0x007510BdDAF1144E4C6c29cD4bC3c0af0ea381a8
0x00A10bF2247556Ca1cDeBF8E66f9994f75A1419D

Request you to please assign KETH . My work is impacting .

Or if there is anyother medium to grab test kovan ethers . Kindly suggest .

Thanks

**Comment by Tbaut** [comment]
I sent you 3 Keth on each account
