### ISSUE TITLE
Faucet service status is not ready now, please resume it.

### ISSUE THREAD

**Issue by vanductai** [kovan-testnet/faucet#24]
Hi @Tbaut ,

Faucet service with gitter (https://gitter.im/kovan-testnet/faucet) is not responding now.

Please help resume it.

Thanks

**Comment by faustogut** [comment]
Hi @Tbaut ,

I have posted post my KETH address on https://gitter.im/kovan-testnet/faucet two days ago but nothing happened. I did not receive any KETH faucet, so I am still waiting for them.

Is that (to wait for days in order to receive Kovan faucet via gitter) normal?

Have I missed any step? Please help. Thanks

**Comment by Tbaut** [comment]
It seems to be down right now, give me your address and I can send you a couple Keth exceptionally.

**Comment by vanductai** [comment]
Hi @Tbaut ,

This is mine: 

- 0xa258139d897a76d4ed889ee32c4a7524d131db8c
- 0x325442a32a18441e20d2a721ef20a9bfeacec794

I can help run a faucet service for Kovan if you need a hand, please let me know.

Thanks

**Comment by Tbaut** [comment]
Thanks, we will make an issue soon to create an alternative.

**Comment by vanductai** [comment]
There are 2 solutions that I can help with this: 
1. SMS Verification via Facebook Account Kit to get KETH automatically
2. Github/Gitlab login to get KETH automatically

**Comment by vanductai** [comment]
Just got 5 KETH each address. 

Thanks @Tbaut

**Comment by Tbaut** [comment]
I deleted your message, I don't want to be the next faucet :) We'll spec out the faucet needs so that it's clear and we'll let you know if we need help, but basically that would be great :)

**Comment by faustogut** [comment]
Hi @Tbaut
This is mine: 
0x7931b12e3623145eCA27B16d6917EE62b4dF1cE0
0xd2515CB383a12E23321820ec9F30E662087FC245
Thanks
