### ISSUE TITLE
Requesting 1 KETH

### ISSUE THREAD

**Issue by l2radamanthys** [kovan-testnet/faucet#265]
I need coin to test integrations
0x456246b18B9edE407913d401784B919de47BC1e1

**Comment by codebrent** [comment]
just sent you 1KEth, I can't get any from faucet either but have a couple surplus

**Comment by renuxsoft** [comment]
> just sent you 1KEth, I can't get any from faucet either but have a couple surplus

do send me some too
0x2030b28AaaF606470C3F6A2b600dC2fc0a34Cbd6
