### ISSUE TITLE
Error Insufficent fund when requesting for funds

### ISSUE THREAD

**Issue by perfectmak** [kovan-testnet/faucet#27]
I got an error when trying to request funds to my kovan wallet. See attached image for details:

<img width="826" alt="screen shot 2018-08-13 at 8 44 56 pm" src="https://user-images.githubusercontent.com/3120013/44054178-d2381180-9f39-11e8-9abb-372b4fd826dd.png">

**Comment by perfectmak** [comment]
I should try this again in 24 hours and close this issue if it doesn't persists

**Comment by Tbaut** [comment]
Thanks for the report. We'll have a look at it and let you know when it's fixed. Waiting 24h is not necessary, it simply means that the account used to send you these KETH has no Ether left.

**Comment by brunocarneiro** [comment]
@Tbaut I had same problem today. However when I tried again on the same day I received the error below even though I haven't received the transation on the second try.

`Faucet draw rate limit reached. Come back in 24 hours`

Seems the code is not checking if the transaction happened successfully.

**Comment by Tbaut** [comment]
>Seems the code is not checking if the transaction happened successfully.

It is not indeed as it's very minimal. The faucet just got some fresh KETH, you can try again (after 24h) or use the Gitter faucet.
