### ISSUE TITLE
Transaction does not succeed because of "Out of gas"

### ISSUE THREAD

**Issue by brunocarneiro** [kovan-testnet/faucet#28]
When I try to get faucet using Faucet.kovan.network the system sends a success message. However looking at the transaction it begins as in pending status and after a long period it gets cancelled. The error message is: "Warning! Error encountered during contract execution [Out of gas]".
Please take a look at a transaction made by Faucet.kovan.network in which this error has happened:
https://kovan.etherscan.io/tx/0xa4b96d8f59a09dd475e011c3e8df5c7fc108bed891723532462ca79833b2c2bb

**Comment by ddorgan** [comment]
Please send the KETH to a real account rather than a contract address.

The faucet wasn't created to estimate arbitrary gas cost.
