### ISSUE TITLE
Sweetbridge wallet beta testing

### ISSUE THREAD

**Issue by drgorb** [kovan-testnet/faucet#29]
Sweetbridge is running a beta program for our Ethereum wallet application. In order to allow our testers to transact, we want to send 1 ETH to every new account which is created. As we plan to get 150 users we need 180 ETH to send them the welcome ETH and be able to confirm transactions (each wallet is a smart contract)

thank you for sending the ETH to 0x8ff329d2b4783048f995dcfadf278759fd3493bf

**Comment by ddorgan** [comment]
Sent: https://kovan.etherscan.io/tx/0x5d67dab0c91d25acba84c010d36b0b2c13b74d71fbdf638aa7298ce966cb15a8

Is this an open source project?

**Comment by drgorb** [comment]
it will become open-source after the release. we keep it under wraps for now. thank you for the transfer. your help is much appreciated
