### ISSUE TITLE
Request for a large amount of Kovan Ether

### ISSUE THREAD

**Issue by igorya7v** [kovan-testnet/faucet#30]
Hello,
My team and I are working on the RightMesh project, you can check the details here: https://www.rightmesh.io.
We have open sourced the blockchain related part of our library, you can check it at our github https://github.com/rightmesh. 
However, the rest of the library code is proprietary. 
We utilise the mRaiden off-chain micropayment channels in our Mesh network library.
We plan a Testnet launch very soon. Scalability is one of the aspects we would like to test, therefore we will need a large amount of Testnet Ether in order to operate large, pushed to the limits Distributed Mesh network.
What is the maximum amount of Testnet Ether you could provide us for this purpose?
And what is the process?

If you have any questions or need more information, please don't hesitate to contact me at igor@rightmesh.io.

Best Regards,
Igor.

**Comment by Tbaut** [comment]
I sent you an email.

**Comment by Tbaut** [comment]
I sent you an email.
