### ISSUE TITLE
Need large amount of KEth 

### ISSUE THREAD

**Issue by xardass** [kovan-testnet/faucet#31]
For our dApp at Swarm City we have our own KEth faucet for new accounts, so they don't have to worry about funding their new accounts with eth to post requests/send tokens.

Right now we try to manually fund our faucet.

Our faucet's address we need this eth on: 0xC5190C86E32938fCD1277d9C779bEB4c0e85d69d

**Comment by Tbaut** [comment]
Is this project open source? Would you mind linking it?

**Comment by kingflurkel** [comment]
@Tbaut Yes, its fully open source.

https://swarm.city / https://github.com/swarmcity

**Comment by kingflurkel** [comment]
@Tbaut And POA helped us bridging our SWT token from mainnet to kovan :)

**Comment by Tbaut** [comment]
Thanks, I contacted you per email @xardass 

>And POA helped us bridging our SWT token from mainnet to kovan :)

That's sweat!
