### ISSUE TITLE
Get large amount of Kovan Ether

### ISSUE THREAD

**Issue by ghost** [kovan-testnet/faucet#32]
Hello. I'm currently working on a project and we need to test 100 000 users with different crypto wallets, including ETH. And for test we need to get 300 ETH. Is there a chance to get such number of Eth

**Comment by Tbaut** [comment]
What project is this? Is it open source? Can you give some links?

**Comment by ghost** [comment]
Hello,

It is not an open source project. We are working for Sirin Labs. Unfortunately, access to the application is restricted.  We are testing one of their applications and for test purpose we need to generate load using significant number of wallets with different coins, including ETH. That’s why I’d like to get mentioned on github amount of Kovan Ether.

**Comment by Tbaut** [comment]
I emailed you
