### ISSUE TITLE
Get large amount of KETH

### ISSUE THREAD

**Issue by KorzhikDM** [kovan-testnet/faucet#33]
Hello Kovan team.
We need a large amount of KETH(about 1000) to test our decentralized funds.
Kovan address: 0xcbea2155a147c7ecf25cad15e8c24b37e0a27511
more info about our project in attached document 

[Product Rocket DAO v1.01 en.pdf](https://github.com/kovan-testnet/faucet/files/2335512/Product.Rocket.DAO.v1.01.en.pdf)

**Comment by Tbaut** [comment]
Is this project open source? Would love to see what you've built already.

**Comment by KorzhikDM** [comment]
In security reasons we use private git but in the future it's going to be open source 
You can see our demo at demo.rocketdao.io 
Also you can download our app https://play.google.com/store/apps/details?id=io.rocketico.mapp
if you want to test our funds with us we can schedule a call:)

**Comment by Tbaut** [comment]
I couldn't send you more than 500 for now: https://kovan.etherscan.io/tx/0xd4f7072e3cb35e3761f39d74e8cd5ac636f014698b83234e6aa66c02d1cd45b6
I hope that's still ok
