### ISSUE TITLE
Get large amount of kETH

### ISSUE THREAD

**Issue by gkaemmer** [kovan-testnet/faucet#34]
Hi!
We're building an augur relayer on 0x (will be launched soon, I swear!), and just moved from rinkeby to kovan. Augur requires a bunch of ETH to purchase complete sets, so would love a large amount of kETH to simulate real markets/order books.

Thanks a bunch.

**Comment by Tbaut** [comment]
Is it open source? do you have a repo to link?
Also what amount would you require? please send me the address you wish to receive it to.

**Comment by gkaemmer** [comment]
Our current project isn't open source so we don't have a public repo, but you can check out some of our other open-source projects here: https://github.com/hillstreetlabs. Lemme know if you need more info.

As much as you could give would be ideal--is 500-1000 kETH possible? We'll use it for development testing in the long term, and I don't want to have to bother you again.

A good address is 0x1d926fedd4e775e00b4479ff1bdc521cc2f19160

**Comment by Tbaut** [comment]
Contacted you per email
