### ISSUE TITLE
Large amount of kETH (0x)

### ISSUE THREAD

**Issue by dekz** [kovan-testnet/faucet#35]
Hey all,

At 0x we run our own faucet for developers to get started exchanging. Our faucet drips 0.1 kETH per request and checks the balance of the receiver to make sure its not over a certain threshold. As such we occasionally need to get a top up.

ETHBerlin and a few other conferences/hackathons (and our v2 launch) is soon approaching. 

If you could top us up at this account 0xea95a7a25506c9F70fB7bC50877C435a609353b2 it would be greatly appreciated.

**Comment by Tbaut** [comment]
Would you consider being an authority on Kovan? We would like to open up the process in the near future (say before Christmas). Please drop me an email thibaut at parity.io to discuss about this and the topup :)
