### ISSUE TITLE
Kovan Faucet Nonce Management

### ISSUE THREAD

**Issue by john-zli** [kovan-testnet/faucet#37]
Not so much an issue, but curious as to how your faucet is able to handle parallel blockchain calls. Do you have your own nonce-management system via web3 subprovider? Or is there something else

**Comment by Tbaut** [comment]
Good question. The load on the faucet is not high enough for us to have this kind of issues (yet?). There is no magic implemented yet. We let the node handle the nonce itself and that's fine so far.

**Comment by ddorgan** [comment]
@johnzli1995  the faucet just uses the call  web3.eth.sendTransaction() to send on kovan eth. 

Nonce management is taken care of internally by the parity-ethereum client itself. Hope this helps....

**Comment by ddorgan** [comment]
@johnzli1995 p.s. if you need to do anything more complicated then I suggest you take a look at: https://wiki.parity.io/JSONRPC-parity-module#parity_nextnonce ...

**Comment by john-zli** [comment]
@ddorgan Gotcha that makes sense. For some reason I assumed you were using an infura host in which you'd need to sign offline, but using a parity node makes sense.
