### ISSUE TITLE
Need KETH for FRENCH-ICO.com BETA TEST

### ISSUE THREAD

**Issue by ghost** [kovan-testnet/faucet#41]
Hello,

I Christophe FRENCH-ICO's CEO and founder and we will start the Beta test of our plateform November 5th, 2018

The plateform is a crowndfunding 3.0 using Ethereum to do the transactions, create an ICO and collect funds. You will see !

The beta test will be used to explain and popularize the blockchain usage.

Because our beta testers won't be only expert having KETH, i would like receive free KETH that i could send to the beta testers

could you send about 1000 KETH to this address : 0x0f6831c8e5d899e5d17fe4426db278cb1f7bb1a1

Send me a email and i will send you invitation for the beta test or register here : http://eepurl.com/dI-2lz 

thanks a lot

**Comment by Tbaut** [comment]
Hi, how many beta testers do you expect to have? probably not 10'000 right?
If you target 500 to 1000, why not giving them 0.1KETH instead of 1 or more?
The idea behind is to prevent users from being able to spam the network for free, we refrain from giving too many KETH at once for this reason.

**Comment by ghost** [comment]
Thanks Thibaut for your answer. You're right and it's why i'm doing actually to adjust the plateform but for the beta test i would like to be realistic and have about 6 first projects why an min cap for each at about 50 KETH and max Cap 100.

So yes 600 Keth should be ok. But i wanted to offer 10 KETH to each 10 first beta testers

Thanks if you want to do somethink

You should know a little bit more today on the website. We're actually upadting the coming soon page with more informations about the project. 

At your disposal if you need to know more

**Comment by ddorgan** [comment]
@French-ICO you cannot do testing with 1 KETH (or even .1 KETH) rather than 10KETH per user? It's all relative....

**Comment by ghost** [comment]
Yes sure, we have now about 100 beta testers registred so it could be great to receive 100 KETH

I could send them 1 KETH at each of them. They don't know probably how to do to collect KETH an di would prefer send to them directly.

Let's start and we will let you know soon if i need more

**Comment by Tbaut** [comment]
100 KETH sent : https://kovan.etherscan.io/tx/0xa90c322880ed2e84c4368f494fdbd4741af7bc95de7d26c57adf73748c36f991

**Comment by ghost** [comment]
thanks a lot @Tbaut :)

the coming soon page is on line : www.french-ico.com

have a look, don't hesitate to participate and give us your opinion
