### ISSUE TITLE
Please provide 1 KETH for contract audit

### ISSUE THREAD

**Issue by drvillo** [kovan-testnet/faucet#42]
Hi there

I'm working on a project aimed at building a rewards & loyalty protocol for eSports and iGaming. My team is testing our contracts on Kovan and there's a series of tests that do require a larger amount of gas to run. These are mostly around stress testing our storage model and to validate the absence of underflows / overflows. 

We still haven't released our codebase to the public but I'm happy to invite you guys to our gitlab repo if you want to take a look.

Thank you, and keep up the good work!
F

**Comment by Tbaut** [comment]
Hey drvillo, can you be more precise regarding the contract?
Even with a really large amount of gas 1000 KETH would allow you to send a crazy amount of transactions. We don't want to give too many KETH at once because of the obvious threat it represents with regards to network spamming. Our Faucet provides 1KETH which is already substantial for normal use, requesting for 1000x seems overkill though.

**Comment by drvillo** [comment]
Hey, shoot I just realized the repetition in the subject lol. It should have been 1 KETH, not a thousand! Just changed it. 

The contract in question tracks participation in the protocol in a radix tree. Based on our tests it takes around 0.06 ETH to perform a whole round of interactions so 1000 ETH would give us capacity for some 16k tests. 

Hope that makes sense. Again, I can share with you some implementation details if you want.

**Comment by Tbaut** [comment]
My mistake, I talk about Kovan ETH, so KETH, and 1 KETH = 1 Kovan ETH.. which is what you can get using a faucet.
We do not give 1000 Kovan ETH at once as this is a threat to the network and as I said even with a really large amount of gas 1000 Kovan ETH would allow you to send a crazy amount of transactions. Would that work with 500 and feel free to ask some more when you need it?

**Comment by drvillo** [comment]
Hey apologies for the late reply. Yeah, let's start with 500. 

You can send to:

0x64BCEf4bB291b980caB7a2088d225F1ed41876A8

Thanks!
F

**Comment by Tbaut** [comment]
Sent https://kovan.etherscan.io/tx/0x95498ba150d099b5c0b51d322d4b8d8edaba362970f7d5a16277d5f151d48600
