### ISSUE TITLE
Need KETH for beta test game RiotCats

### ISSUE THREAD

**Issue by vecheslav** [kovan-testnet/faucet#43]
We wanna using kovan for our game (https://riotcats.co). For beta test we require large volumes.  Thanks!
Our address: 0xd23b909181f4cb24c060cd2b3007033445b46bbc
We would like receive free KETH that i could send to the beta testers.
Ideally we would need at least 1,000 test eth.

**Comment by ddorgan** [comment]
@vecheslav looks cool! Is this open source btw?

**Comment by vecheslav** [comment]
> @vecheslav looks cool! Is this open source btw?

Yes, we wanna start bounty for source in the future :)

**Comment by ddorgan** [comment]
@vecheslav URL for the code?

**Comment by vecheslav** [comment]
> @vecheslav URL for the code?

https://github.com/vecheslav/riotcats-bounty
it's not all code, will add more extensions.

**Comment by ddorgan** [comment]
500 sent: https://kovan.etherscan.io/tx/0x004051d887ecb3f2a994495a21d5149d3d013ed78d7c2ad358f62d9eb6187d7a
