### ISSUE TITLE
Request for KEth (Raiden Network)

### ISSUE THREAD

**Issue by ulope** [kovan-testnet/faucet#44]
Hi,

we'd like to expand our testing of the [Raiden Network](https://github.com/raiden-network/raiden) to Kovan.

So far we've been running manual one-off tests with keth from the faucets and have been very happy with the speed (esp. compared to Ropsten).

However our automated tests include many test scenarios, some with a lot of nodes (each of which requires their own account with a minimum required deposit).

Therefore we'd be grateful if you could provide us with, say 500 KEth or so.

Thanks!

**Comment by Tbaut** [comment]
Sure, what's your favourite address?

**Comment by ulope** [comment]
`0x00A33749a231f2e9c10deFE83403a67148D38438`

**Comment by Tbaut** [comment]
On their way https://kovan.etherscan.io/tx/0x22a78f806292ef405359171109c5b83487e8e49240e5ffa0c01c4cdda1a306a0

**Comment by ulope** [comment]
Great, thanks a bunch!
