### ISSUE TITLE
Request for Kovan ETH

### ISSUE THREAD

**Issue by bala007** [kovan-testnet/faucet#45]
Hi Guys,

We recently switched from Ropsten to Kovan, so far very happy with the syncing and speed.
Also we want to do a load test on our side chain. It require to fund lot of worker processes. It would be great if you guys provide 200 Kovan ETH to the following address:
0x464d8510c78ca1c53a9dcca21ef88d42652cc12c

Thanks,

**Comment by Tbaut** [comment]
Hey, can you tell us more about the project? is it open source?

**Comment by bala007** [comment]
Yep, it is open source. 
https://github.com/OpenSTFoundation
https://openst.org

OpenST is working on scalability and usability solutions for running high volume applications on Ethereum.

The **OpenST Protocol** enables building scalable blockchain token economies through the transposition of tokens via gateways between Ethereum and utility blockchains. The protocol also includes components that enable economy administrators to design token-economies to support their community and business goals.

**OpenST Mosaic** is a layer II protocol for scaling Dapps on Ethereum by running meta-blockchains on Ethereum to scale to thousands of transactions per second.

**Comment by Tbaut** [comment]
Eth on their way https://kovan.etherscan.io/tx/0x5580330e27bf5f24bfabd55a123075da69efacdec053ac338bdf3135490e8847

**Comment by bala007** [comment]
Thanks!
