### ISSUE TITLE
Large sum of KETH for community test

### ISSUE THREAD

**Issue by MatthijsDeVries** [kovan-testnet/faucet#47]
Hi,

We have a (closed source) platform (on Gitlab), of which we are very close to launching the MVP of. We have a steady following of 300 users, and expect around 1000 users that will actively test the platform.

More information about us: https://www.allianceblock.io/

We are building a platform for new and experienced investors to safely invest in any projects with a relation to blockchain (and later with no relation to blockchain), in a way that makes sense in 2018 and beyond. No more large amounts of money getting stolen, no more projects that receive millions and don't deliver (we implement a funding mechanism based on milestones) and no more confusion about how to invest and what to do next or how to decide which project is good or not. All of this is based on the community itself, which has a final vote in what happens next to a project and its investment round. The community has a very large and prominent role in all of this.

Obviously the funds are distributed through smart contracts, created on the fly (automatically by the platform, tailored to the needs of the specific project). When tokens are distributed, they can be swapped for other tokens, so that waiting very long for an exchange listing is not really needed anymore.

In order for the community to test our platform, they'll need some funds to get them started on investing in projects so that they can collect tokens and swap them amongst each other.

I expect that we will need between 1-2 KETH per user.

Thank you in advance,

Best regards,
Matthijs
Co-Founder
AllianceBlock

**Comment by Tbaut** [comment]
Thanks for your interest. I believe that the different faucets available today are what you need to get started: https://github.com/kovan-testnet/faucet

Each participant can request ETH this way. We foster open source projects and would love if you can open your code.
