### ISSUE TITLE
Requesting 500 kovan eth for testing 

### ISSUE THREAD

**Issue by zhen6939** [kovan-testnet/faucet#49]
Hi there,
I come from imToken, ConsenLabs, a mobile wallet app with 7m users. 
We are building some new features, so that need 500 kovan eth for testing.

wallet address：0xcc0f9D680C48BC785B7a7b6155b37AbeAE191290

Would you like to support us?

BTW: we just published our core repo.
https://github.com/consenlabs/token-core-ios
https://github.com/consenlabs/token-core-android

Many thanks

**Comment by Tbaut** [comment]
Hey Caizhen,
Thanks for your interest, I'm glad to read you guys want to experiment.
Can you let me know what you guys are using Kovan for?
Cheers

Tx: https://kovan.etherscan.io/tx/0x13d1165382e40cb17612e90f3740a2737a976acd2d85b29e78e75cc2c79b54bf

**Comment by zhen6939** [comment]
Thanks for the ether!

Actually, we are optimizing Tokenlon user flow, which is a build-in decentralize exchange in imToken, so that we need tons of kovan eth to simulate the real environment

Cheers
