### ISSUE TITLE
30 Keth for Provenance Dapp

### ISSUE THREAD

**Issue by v-stickykeys** [kovan-testnet/faucet#51]
Hi there!

I'm creating a dapp where you can register archeological antiquities on-chain to help prove their provenance. It is all open source, and you can see the work I've done so far here: https://github.com/GlobalXplorer/gxregistry

Would be really helpful to have keth sent to the following accounts that I am using for transactions and deployment:
10 keth -> 0xf6003510c33d32e07d7065d098328500e668b0a7
10 keth -> 0x3ddb790ddb61bae8f7a8a24afb90254a490dd15c
5 keth -> 0xf6d4fc07182d9a837636e357d1cfb4c58b290095
5 keth -> 0x23df565dcc0f065036bc888b4081c02b2c764112

Let me know if there is more info needed!
Thanks

**Comment by Tbaut** [comment]
Interesting project, thanks for the interest. I've sent you 31 to the first address and let you shuffle the ETH around the way you want.
https://kovan.etherscan.io/tx/0x2b5eadb799cf13205dccd8421f2cbb920717c0b2c16ca30145055d5d346db5d2

**Comment by v-stickykeys** [comment]
Thanks @Tbaut !!
