### ISSUE TITLE
500 KETH for Lendflo

### ISSUE THREAD

**Issue by Remi-Tuy** [kovan-testnet/faucet#52]
Hello,

We are from Lendflo (www.lendflo.com), we are building a P2P invoice financing platform, based on the Dharma protocol. A lot of our work is developing new terms contract for dharma to enable new functionalities such as crowdfunding, bound issuance, etc...
We would need about 500 KETH to improve our development speed as it is simply not efficient to have to ask the faucet every 2 days.

The address is: 0x48DB19CdDE130943E9050c91a95Aa8335A8E5785

Best,

RT

**Comment by Tbaut** [comment]
Hello,
Is your project open source? I couldn't find any Github link on the website

**Comment by Remi-Tuy** [comment]
It is not Open Source, we are building on Open Source tech, ei. dharma protocol and cetrifuge.io and contributing to their project, but our tech is not open source.

**Comment by Tbaut** [comment]
Our Github based Faucet gives 1KETH every 24h max. I understand that this is not ideal for constant testing, but I wonder how many ETH you really need. Sad to read your project is not open source. 500KETH is a huge amount of transactions you can make, this also represents a threat to the network should they land in the wrong hands. [Sent you 100](https://kovan.etherscan.io/tx/0xc0fd40b9765492742ae5b440cba2b55d977c5786a8fff61e53b58e2b1c2ef1899 to start with, feel free to ask for more when you need it:
