### ISSUE TITLE
50 keth request

### ISSUE THREAD

**Issue by banannn** [kovan-testnet/faucet#53]
Hi,
I'm working for Cirravia (http://cirravia.com/) and we are building dapp for our client to receive payment in ether for airline tickets through smart contract.
We want to make some E2E tests with real ticket prices so some ether would be very useful as faucet seems stopped to work.

Our smart contract is not open sourced yet.

Address: 0x9cF7C9EFaF79A211d704437b00A8C6212EeaB354

**Comment by Tbaut** [comment]
Thanks for the heads-up, we're checking. I've sent it: https://kovan.etherscan.io/tx/0x9cf7df2c80874853eda0f7009cd358e070124ce917ce4a20d9764cb92c9e44f4
