### ISSUE TITLE
Lots of KETH for TokenCard please :)

### ISSUE THREAD

**Issue by mischat** [kovan-testnet/faucet#54]
Hello, 

I'm CTO of TokenCard, one of the early Ethereum projects. We are looking to start deploying the first version of our Smart Contracts to Kovan, any chance we can have a lot of KETH please? Let me know if you would like more information. We would be looking to invite lots of users to test our alpha version of the app?

**Comment by mischat** [comment]
Here is my public key : 0xF1276c6B381908e6dEdC869Bd4deFa8eB9Ca8F03

**Comment by Tbaut** [comment]
Hey Mischa, Cool project :)
How many user do you expect to reach?

**Comment by mischat** [comment]
Thank you. 

I guess, I will get back to you on this shortly, so please don't send us KETH just yet :)

If we do start inviting people to this public alpha, I would say that there would be hundreds of people testing our App + Smart Contracts :)

We are just figuring out which of the testnets is the best for our testing. We understand that there is no ENS on kovan and if we end up going with Kovan, we might just deploy ENS to the network ourselves.

So, thanks for bearing with me here, and I will get back to you on this thread shortly. I hope this is cool?

**Comment by Tbaut** [comment]
sure

**Comment by mischat** [comment]
Hi Tbaut, thanks for responding. As it stands I think we are going to give Ropsten a go, to give something with proof of work. But we might come a knocking sometime soon.

**Comment by Tbaut** [comment]
fine by me.
