### ISSUE TITLE
20 kETH for Team testing Contracts

### ISSUE THREAD

**Issue by hav-noms** [kovan-testnet/faucet#55]
Can you please send 20 KOVAN ETH to 0xaF28CEC7854e9a070F4cD31F18bA005F874d9F50

I can distribute to the team as we build and test our token exchanger contract Depot.sol
https://kovan.etherscan.io/address/0xa9366cf9b0eb616b46771a41bb04e42d12c0f1fa#code

we also need this for our multi-currency stablecoin release this month
https://github.com/Havven/havven/tree/multicurrency

**Comment by Tbaut** [comment]
Sure, https://kovan.etherscan.io/tx/0x3936ed6092f801bcee6a378a11869b6f5ad8b4af2d5b2388e267cdf771d901ef
