### ISSUE TITLE
100 KETH for testing request

### ISSUE THREAD

**Issue by 0x234** [kovan-testnet/faucet#56]
Hello Kovan,

I work on the DevOps team at OmiseGO and we're building an implementation of Plasma MVP, a layer two child chain solution for scaling transactions with Ethereum. We're evaluating different Ethereum clients and testnets and we'd like to try Parity on Kovan.

Here is our project website: https://omisego.network/
The service we will be deploying is here: https://github.com/omisego/elixir-omg/

Public key: 0xd8B74E8f99bE2ae26988e6bA876A0B73872c47D6

If you would like any further information please feel free to ask.

Thanks

**Comment by Tbaut** [comment]
sure, thanks for using it. 
https://kovan.etherscan.io/tx/0x4dc7310838350436d063b3aa8265eff05c5b1658cce55f39f1844ae059c4be1f
