### ISSUE TITLE
120 keth request for testing

### ISSUE THREAD

**Issue by knaub-am-bau** [kovan-testnet/faucet#57]
Hello Kovan,

We are the Midas Technologies AG from Zug, Switzerland.
At the Moment we develop an app on top of the Melon Protocol.
For our tests on the Kovan net, we would like to have 120keth

Here is our project website: https://midas.social

Our wallet address is:  0x10BaeeFCaeb6dd00F65230DFc0Ba3331d000373A

If you would like any further information please feel free to ask.

Thank you.

**Comment by Tbaut** [comment]
On its way: https://kovan.etherscan.io/tx/0x635cc8fc017de27515caeff8b7f12fff4645fd3968a78206180560c8988134d2
