### ISSUE TITLE
Fifty KETH Request 

### ISSUE THREAD

**Issue by Gendau** [kovan-testnet/faucet#58]
Hi Kovan
We are a software company that is developing an application for storing certificates on blockchain. We have previously developed the solution on Etherscan Ropsten but is migrating to Kovan for the POA consensus mechanism. We would need some extra KETH as we need it during our regression testing. 

Would it be possible to transfer 50 KETH to 0x1502f9009b98CCdf6CF503152Bc7f22ECBBdb3CC

**Comment by Tbaut** [comment]
Sure, sent with :heart: from [fether](https://github.com/paritytech/fether)
https://kovan.etherscan.io/tx/0x75eff59f934153f13af33a3d88c36e16702d69f8c4f9142dd6ed21c726175cb5

**Comment by Gendau** [comment]
Many thanks!
