### ISSUE TITLE
Fifty KETH request

### ISSUE THREAD

**Issue by Gendau** [kovan-testnet/faucet#60]
Hi Kovan
I previously requested 50 KETH for our application which stores certificates on the blockchain which was kindly granted. We needed the 50 KETH for regression testing our new application and we have 10 KETH left after our testing. On Friday we have a big three-day event where we want to present our solution and we are worried we will run out of KETH. 

Would it be possible to transfer an additional 50 KETH to 0x1502f9009b98CCdf6CF503152Bc7f22ECBBdb3CC

**Comment by Tbaut** [comment]
Hi Gendau, you've been regularly distributing 1KETH (to users?). All addresses you've been sending 1ETH to still have at least 0.99 ETH on it today..
Please consider using the faucet for it https://faucet.kovan.network/ or give them less, with 0.1 ETH it is enough to perform many transactions already, and keep your KETH for testing.
I've sent you some more but please consider adjusting your testing system to use them more wisely. https://kovan.etherscan.io/tx/0xeba1c9a2e2594316383497026c288bcc378b8bfe13096732129c45988748b7a5
