### ISSUE TITLE
Need a bit more kether

### ISSUE THREAD

**Issue by knaub-am-bau** [kovan-testnet/faucet#61]
Hello Kovan,

We are the Midas Technologies AG from Zug, Switzerland.
At the Moment we develop an app on top of the Melon Protocol.
We have got 120keth from you for tests on the Kovan net. During the preq. for the alpha, 
we learnd the 120 was a bit short calculated. Could you transfer us another 120 kether?

Thank you.
 
Here is our project website: https://midas.social

Our wallet address is: 0x10BaeeFCaeb6dd00F65230DFc0Ba3331d000373A

If you would like any further information please feel free to ask.

Thank you.

**Comment by Tbaut** [comment]
Hi, you've not used the first 120 yet as I can see, can you tell me more about what it will be used for?

**Comment by knaub-am-bau** [comment]
Hi, sure.
We invited test user, they will have test wallets (to use the app). and we need to give everyone the same amount, at the same time. First we calculated to give every test user 1 Keth, but now we saw its a bit too less.

If you want further infos, pls ask. we are happy to give you the information.

Thank you.

**Comment by Tbaut** [comment]
How can 1 KETH not be enough? Unless you expect each user to perform 500 transaction with a costly contract, 1KETH is most prob. more than enough from my perspective.

**Comment by knaub-am-bau** [comment]
I had a coversation with the team. They say we will expect more then the 120 users. (I didnt have the info before I wrote you, just that we need more). They said 50 keth would also do it, but then maybe we have to ask you a third time.

Thank you.

**Comment by Tbaut** [comment]
I've sent you 100 more https://kovan.etherscan.io/tx/0x9e7bfabe2e8e562157852193ddcf73678e9e88f4e472399cc28d215a41bb4741 feel free to ask should you have some new needs ;)

**Comment by knaub-am-bau** [comment]
Hi.
Because of the place order situation on Oasis Stack on Kovan, there are not many orders you can make with under 1Keth. So I wanted to ask you for another round of Keth. With our coming numbers of test users, our keth wouldn't be enough for all of them.

Thank you and feel free to ask any question about our project if you like.
