### ISSUE TITLE
How can i get erc20 token usdt on kovan testnet

### ISSUE THREAD

**Issue by ruguo220088** [kovan-testnet/faucet#63]
I'm running: Parity v2.1.9-stable
Which operating system?: MacOS
How installed?: via installer
Are you fully synchronized?: yes
Which network are you connected to?: kovan
I dont konw how can i get some testnet erc20 token like "testnet Erc20 token--Tether USDT" which token not i generate.
From website there is somebody said: you can tranfer ether to erc20 token contract address, then contract will give you some erc20 token.
but when i did like before, i keep receiving the following:
Contract 0xd92eee71478e115fcc5342fa44242e7896b8af3b
Warning! Error encountered during contract execution [Reverted]
Can someone please help...

**Comment by Tbaut** [comment]
I'm not sure what you're trying to achieve. Kovan is a testnet where ETH is free (it has no value, it's there to test). To receive test ERC20 tokens on Kovan, you can see here for instance: https://0xproject.com/portal
This repo is not the right place to ask though as it is dedicated to provide Kovan ETH.
