### ISSUE TITLE
50 kETH Request for Dapp testing sales for ETH

### ISSUE THREAD

**Issue by hav-noms** [kovan-testnet/faucet#64]
We're testing our minting stablecoin and new peer 2 peer selling for keth. We're simulating clearing out the order book on USD in the thousands of dollars. 

You can try it out also on KOVAN 
https://staging.mintr.synthetix.io/

**Comment by Tbaut** [comment]
Hey sure, is the project open source?
What address would you like to receive them?

**Comment by hav-noms** [comment]
Absolutely it is open source https://github.com/Havven/havven

Could you please send them here 0xaF28CEC7854e9a070F4cD31F18bA005F874d9F50

Cheers!

**Comment by Tbaut** [comment]
cool, just [sent it](https://kovan.etherscan.io/tx/0x974c127caf94372195d8953ba4cf6354f06a237baa08d07537ec89ddf494529c) (with :heart: using [Fether](https://github.com/paritytech/fether))
