### ISSUE TITLE
Request for KETH

### ISSUE THREAD

**Issue by AntoBrajkovic** [kovan-testnet/faucet#65]
Hi,  
We are working on 0x and OpenRelay based DEX. 
Our website, altcoin.io
Our repo(most of the 0x stuff is currently not open sourced), https://github.com/AltCoinExchange/

We need 100 KETH for internal testing off the exchange.

Kind regards :)

**Comment by AntoBrajkovic** [comment]
Forgot the address: 0xb06F42c825C18CA0c343b99ed8f9639bAfdD571d

**Comment by Tbaut** [comment]
:) [done](https://blockscout.com/eth/kovan/tx/0xc87c971a95428f77a497a86c4e669e3e1ed985c35501877a01bd083567a43ad0/internal_transactions) with :heart: using [Parity Fether](https://github.com/paritytech/fether)
