### ISSUE TITLE
Creating a universal faucet

### ISSUE THREAD

**Issue by JesseAbram** [kovan-testnet/faucet#66]
Hey, we have created a universal faucet......currently it only has AION but it is ready to go to production with Kovan we just need a supply of tokens. https://faucets.blockxlabs.com/ .

**Comment by JesseAbram** [comment]
I guess 1000 would be great to start, eventually would love to get a pipeline going if the request pick up 0x77488ed6c9448E1A5dBe6772d6D31dB85108A53E.  Thank you!

**Comment by Tbaut** [comment]
Hi, the reason we have faucets using some kind of authentication is to prevent sibyl attack on the faucet and then flooding the network. From what I can see you do not have any such authentication and you want to give away 10 ETH per address, that is quite big considering the amount of transactions you can do. This represents a threat to the Kovan network.

**Comment by JesseAbram** [comment]
I understand the concern, We do a captcha verification to make sure bots can't request as well we have a 24 hour limit per address. We wouldn't give away 10 eth for kovan because the cost semantics are different than what AION's are. We were thinking more along the lines of of <= 1

**Comment by Tbaut** [comment]
That sounds good, thanks for the answers. I'd like to start on the safe side by sending you 200 and we can top that up as soon as you need it. We're quick to react. Does it sound OK?

**Comment by JesseAbram** [comment]
Ya that is amazing, thank you so much, and if you have any suggestions to make the faucet better please let me/us know, cheers!

**Comment by Tbaut** [comment]
Thanks, I'll take a look, I very much like the idea, searching for faucet remains a PITA today :)
Transaction [here](https://blockscout.com/eth/kovan/tx/0x56aea093a29042e464221315c91ac4f3330a98ac02a61adb1d08e71bccba7170/internal_transactions) sent with :heart:  using [Fether](https://github.com/paritytech/fether)

**Comment by JesseAbram** [comment]
Hey, I just wanted to day thank you and that Ethereum has been integrated. Would love any other feedback or leads for other coins/tokens. Also I noticed you sent me to blockstout. We defaulted to using etherscan but more than happy to change if you'd like. https://faucets.blockxlabs.com/

**Comment by Tbaut** [comment]
The restriction to send 1ETH per address per 24h is too easy to circumvent IMO, creating a new ETH address takes no time. This is why we actually request a GitHub login.
The reason why we chose to use blockscout is because it's open source and takes more care of its user's privacy https://github.com/poanetwork/blockscout/issues/1274#issuecomment-451861976
