### ISSUE TITLE
Request 200 ETH for dApp testing

### ISSUE THREAD

**Issue by nitika-goel** [kovan-testnet/faucet#69]
Hi,
We have been building a P2P insurance platform Nexus Mutual (https://nexusmutual.io/) on Kovan testnet for more than a year now and are now moving towards production. .We need large amounts of ETH to test the application module for use cases like purchasing of cover, stakes forclaims assessment, risk assessment, claim payouts, insurance pool investment diversification using Uniswap.

It would be super helpful if you could transfer around 200 ETH at 0x7266C50F1f461d2748e675B907eF22987F6B5358. If you can spare some more for us, there would be nothing like it ;)

The project is open sourced at https://github.com/somish/NexusMutual.

Thanks

**Comment by ddorgan** [comment]
Hi Nitika,

             Thank you so much for the information. KETH sent: https://kovan.etherscan.io/tx/0xc8ce26c11493adf66f17ee8086d2e55982d3881b06444d050a1256aafba387f9

Thanks,
David
