### ISSUE TITLE
is http://github-faucet.kovan.network/ down?

### ISSUE THREAD

**Issue by zdrr** [kovan-testnet/faucet#7]
```
curl http://github-faucet.kovan.network/url --data "address=https://gist.github.com/zdrr/b3b742d996c0071052abdbe0a5e98e47"
curl: (7) Failed to connect to github-faucet.kovan.network port 80: Connection refused
```

**Comment by ddorgan** [comment]
Can you re-try this now? Should be resolved....

**Comment by zdrr** [comment]
Sorry for the delay.
Thank you, now it's working :)

**Comment by ivan-baranovski-intellectsoft** [comment]
This is reproducible today
`curl http://github-faucet.kovan.network/url --data "address=https://gist.github.com/ivan-baranovski-intellectsoft/829d02170f9e98fa36b9b8919a614596"
curl: (7) Failed to connect to github-faucet.kovan.network port 80: Connection refused`

**Comment by ddorgan** [comment]
This has been taken down on purpose. Will create an alternative this month.

For now you can use the email or sms verification, or the gitter channel.

**Comment by ivan-baranovski-intellectsoft** [comment]
Thanks.

**Comment by Sell92** [comment]
0xd2e48a8F05D77cc1543a923EDA197A1a0c830744
