### ISSUE TITLE
Request 50 keth for dApp testing

### ISSUE THREAD

**Issue by gnorbsl** [kovan-testnet/faucet#70]
HI,

we are working on a crypto based way to buy beer and I would like to have some keth for testing.

https://craftbeercoin.info/

The project is not open source though. I hope thats not a problem.

Thanks!

kovan address: 0x6e28F4b0f2Fc254c0512c41387bC5d68AFCf4F8a

**Comment by Tbaut** [comment]
Open source should be the way to go for everything blockchain if you ask me. The faucet is there for you to get Keth for testing, please let us know why you need more than what is provided.

**Comment by Dogsnack** [comment]
learning would like some keith

**Comment by Tbaut** [comment]
stale
