### ISSUE TITLE
Request 500 KETH for funding Uniswap exchange on Kovan

### ISSUE THREAD

**Issue by nitika-goel** [kovan-testnet/faucet#73]
Hi, I need to fund Uniswap's DAI exhange on Kovan to test out my project Nexus Mutual's integration with Uniswap. 
Uniswap's code base is available at https://github.com/Uniswap/contracts-vyper. 
The Kovan setup of uniswap is available at https://hackmd.io/OlNJB9a-QJCn8t9BfpOOfg?view. It's low on liquidity currently.

Nexus Mutual code base is available at https://github.com/somish/NexusMutual/.

Your help would be really help projects building on Kovan and want to test out Uniswap for exchange of tokens. 

Please send KETH to address 0xED2F74E1fb73b775E6e35720869Ae7A7f4D755aD

**Comment by Tbaut** [comment]
Sent with :heart: using [Fether](https://github.com/paritytech/fether): https://blockscout.com/eth/kovan/tx/0xe45c62a7cb49ca9dabe6eafb0c1f624b298e33c037f3a7872ca594c681703e90/internal_transactions

**Comment by bwheeler96** [comment]
Is there a public version of Uniswap on kovan? I'd like to use it, happy to help
