### ISSUE TITLE
Request 300 keth for SC testing

### ISSUE THREAD

**Issue by stupidlovejoy** [kovan-testnet/faucet#74]
HI!

I am a smartcontract developer and I need more keth to test at different addresses of contracts being developed.

My current account: https://rinkeby.etherscan.io/address/0x3c64B86cEE4E60EDdA517521b46Ac74134442058

Thanks!

Kovan address: 0x3c64B86cEE4E60EDdA517521b46Ac74134442058

**Comment by Tbaut** [comment]
For what project? Why would you need more, 1ETH now and then should be enough for a lot of contract deployments and transactions
