### ISSUE TITLE
Request 100 KETH for ICO testing

### ISSUE THREAD

**Issue by sirius316** [kovan-testnet/faucet#75]
HI!

I need 100 KETH to ETH token ICO test.

My current account: https://kovan.etherscan.io/address/0xd4e99a670832d52d2c09dd2dcf2e302fe748e6df

Kovan address: 0xd4E99A670832D52d2c09dd2DcF2e302FE748e6DF

Thanks!

**Comment by Tbaut** [comment]
What is you project? Is is open source?
