### ISSUE TITLE
Need for more Keth

### ISSUE THREAD

**Issue by knaub-am-bau** [kovan-testnet/faucet#76]
Hi.
Because of the place order situation on Oasis Stack on Kovan, there are not many orders you can make with under 1Keth. So I wanted to ask you for another round of Keth. With our coming numbers of test users, our keth wouldn't be enough for all of them.

Thank you and feel free to ask any question about our project if you like.

_Originally posted by @knaub-am-bau in https://github.com/kovan-testnet/faucet/issues/61#issuecomment-464713160_

**Comment by Tbaut** [comment]
I've sent you some more: https://blockscout.com/eth/kovan/tx/0x470a180ce97022d38eb9fd77422ef05df8642a11f759bc83dabd67334ee7f141/internal_transactions

**Comment by knaub-am-bau** [comment]
Hi, its us again.
We are in need for more KEth.

The reason for that is that we have more testers in the alpha. And like I explained in the previous issue, it is quite expansive what we are doing.

Thank you very much.
