### ISSUE TITLE
Requesting More Keth for the Universal faucet 

### ISSUE THREAD

**Issue by JesseAbram** [kovan-testnet/faucet#78]
Hey, me again, things have been going well, if you don't mind can we get a topup?

[https://faucets.blockxlabs.com/](url)

address: 0x2cbd2887cF19d6e26284944386Bf8B8D60dEb45c

Thank you!

**Comment by ddorgan** [comment]
@JesseAbram can you please ensure you have some sort of rate limiting per user. Right now you can create as many accounts as you want and get 1 KETH per account. Quite a serious issue. We personally link the address and the github account (with oauth) and limit the withdraw to once per day for both.

**Comment by JesseAbram** [comment]
Understood, we are now talking about ways to implement this without hindering our users so much. Also personally I want to steer away from github as I feel that a faucet can be used to train non developers how to use the blockchain and don't want to limit access. Anyways thanks for your time, I will close the issue and reopen it when we have implemented something

**Comment by ddorgan** [comment]
@JesseAbram thanks for the update. If you don't want to use the github route there are some other services in use by other faucets that include Twitter, Google Plus or Facebook. But basically anything that ties one address to one other external account (oauth is easy) and limit requests from this pair to one request per 24 hours works well.

An example (in nodejs) is to simply fill in an array with a timestamp and check if that is older than 24 hours (see: https://github.com/paritytech/sms-faucet/blob/master/server.js#L51).

I don't mean to discourage you, the project looks great and makes sense, but it should really have basic sybil attack resistance.

**Comment by JesseAbram** [comment]
Hey, We have built a login and put Ethereum behind it. It requires email verification. If possible would appreciate more funds!  0x953A04806503dA87Fa5c5e79e7fBcaDa6dd581Bd

**Comment by JesseAbram** [comment]
Hey, starting to run really low on KETH......and your gitter faucet is currently down, not sure how much longer we can support Kovan without a top up please and thank you.

**Comment by ddorgan** [comment]
@igorbarinov who takes care of these requests from now on?

**Comment by igorbarinov** [comment]
Sure we can top up. What is a monthly usage ?

**Comment by JesseAbram** [comment]
Hey, roughly 300 hits a month and we want to mimic the gitter faucet so like 1 eth every 2 days, so 150 eth would be great. This is our stash account we would prefer the funds were sent to "0x953A04806503dA87Fa5c5e79e7fBcaDa6dd581Bd"

**Comment by igorbarinov** [comment]
@JesseAbram cool. I've sent you 50,000 KETH from POA Validator reward https://blockscout.com/eth/kovan/tx/0x2bc50f01b2b837ef1b5b9aaf37a91615ea4a75adf6648d93b6168337dd06f911/internal_transactions

**Comment by JesseAbram** [comment]
Thank you so much!
