### ISSUE TITLE
100 KETH for 15 Stablecoins and synthetix asset testing

### ISSUE THREAD

**Issue by hav-noms** [kovan-testnet/faucet#79]
0xB64fF7a4a33Acdf48d97dab0D764afD0F6176882

For testing a new release of the smart contracts behind https://synthetix.exchange/ and https://mintr.synthetix.io/
by https://www.synthetix.io/

opensource stablecoin smart contracts https://github.com/Synthetixio/synthetix

**Comment by Remi-Tuy** [comment]
@hav-noms did you guys manage to get some KETH ? Seems like no body is replying on here :'(

**Comment by hav-noms** [comment]
@Remi-Tuy Nope. We did on the first request. We had the good folk at another project lend us 100 rETH for ropsten testnet

**Comment by ddorgan** [comment]
@hav-noms https://kovan.etherscan.io/tx/0xccf241ef1da6dcabefa2052d9551724407f19b120e5d4084cb16cc45b7ba289d
