### ISSUE TITLE
CURL REQUEST NOT WORKING

### ISSUE THREAD

**Issue by somish** [kovan-testnet/faucet#8]
I try getting ethers using the following:
curl http://github-faucet.kovan.network/url --data "address=https://gist.github.com/support-somish/fea2775ff97a0af2438b6617b37fb5b3"

It says  "Failed to connect to github-faucet.kovan.network port 80: Connection refused"

**Comment by ddorgan** [comment]
Can you please check now.

**Comment by somish** [comment]
It's working now. Thanks!
