### ISSUE TITLE
Internal error: Error: Insufficient funds

### ISSUE THREAD

**Issue by TheCount** [kovan-testnet/faucet#80]
When I tried to request kovan ether via the faucet, I got:

> Internal error: Error: Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 1000031000000000000 and got: 675218397756136907.

The "related issues" feature of github brings up #27, and there it could apparently be fixed by refilling the faucet account.

**Comment by ddorgan** [comment]
Resolved...
