### ISSUE TITLE
100 KETH to let users test our app before using real ETH

### ISSUE THREAD

**Issue by elliotolds** [kovan-testnet/faucet#82]
Can we get 100 KETH to 0x3B2250c9ED58844A1CEF27a70619a246489af753 for an app we're about to launch? We want to run our own faucet integrated within our app to enable a "test mode", where users can try out our app without having to send real ETH to our contracts. Our faucet will require that users link a Facebook or Twitter account to their Atstake account before we give them any KETH.

The app will be at atstake.net (just a 'coming soon' page now -- you can see a tentative splash page at itsadeal.app), and will allow users to stake crytpo and their reputations on their fulfillment of p2p agreements. Our app's smart contracts are here: https://github.com/atstake/atstake/tree/master/contracts

**Comment by elliotolds** [comment]
Hi -- we are hoping to launch within about a week and want to have our faucet working by then. Do you need any more info to approve this request? If it's the kind of request that will be approved, can we get an ETA?

**Comment by Remi-Tuy** [comment]
@elliotolds did you guys manage to find a supply ? Looks like this faucet is dry and we are really looking for some as well.

**Comment by ddorgan** [comment]
@elliotolds https://kovan.etherscan.io/tx/0x727ea79502860b8237016572dfe3ba14696e6ed1502154811d682cc611e1c7d8

**Comment by tonnypham94** [comment]
Could you help me to get 2000 KETH? I know its a big amount of KETH but my team have to get it to test ours code because we have to create more users. Thank you very much!
My address: 0x93ada4ba1c6eab6fa83f366952a81b1a5d711ad4

**Comment by sadamsid01** [comment]
I need 500 KETH for testing. 
My address: 0x4978855e6998192CEe3aC1C3BfdD3C009521C003
