### ISSUE TITLE
Request for 50 KEth for Lendflo

### ISSUE THREAD

**Issue by Remi-Tuy** [kovan-testnet/faucet#84]
I have previously described the project, Lendflo builds a P2P crowdfunding asset collateralized debt platform. We have built on top of Dhara our own Terms contract and architecture.

The project Solidity code is not open source yet, but the website is here www.lendflo.com

Could we have another 50 KETH to this address plz: 0xF5391d6E7224B0b7faF9Cbf7932B0B91cdaE4487

**Comment by Remi-Tuy** [comment]
@ddorgan  Hey guys, let us know if you need anything from us regarding this request.

**Comment by ddorgan** [comment]
Done: https://kovan.etherscan.io/tx/0x2970dd82cec9e592cb63c69e57f2ee654da53090ad294ff92d74ecf061b29115

**Comment by ddorgan** [comment]
Done: https://kovan.etherscan.io/tx/0x251eef7e963041350413f66f02f2323db02622ecc4c778b2750325baf15e5eb3
