### ISSUE TITLE
Request 100KETH for Enigma Testnet Launch

### ISSUE THREAD

**Issue by fredfortier** [kovan-testnet/faucet#85]
Enigma is a layer 2 network for private computations. We've selected Kovan to host our testnet. We will be selecting initial node operators by running a competition on the testnet. In a nutshell, we'll  send random transactions to these node operators to evaluate their average response time and uptime. We need KETH to cover the gas cost of sending those tasks. This will not overwhelm Kovan. The competition will last for several weeks. We will create a few transaction per hour. Feel free to ask any questions.

Here is one of our main repos: https://github.com/enigmampc/enigma-core

**Comment by ddorgan** [comment]
@fredfortier which address should it be sent to?

**Comment by ddorgan** [comment]
No reply, please re-open if you still need KETH.
