### ISSUE TITLE
Faucets are down

### ISSUE THREAD

**Issue by APshenkin** [kovan-testnet/faucet#86]
Hi!

https://faucet.kovan.network show that transaction created, but it's not true

https://gitter.im/kovan-testnet/faucet sending request to gitter also not working

**Comment by vincentmacri** [comment]
https://gitter.im/kovan-testnet/faucet is now working, but https://faucet.kovan.network/ is still broken for me too.

**Comment by ddorgan** [comment]
@APshenkin this has now been resolved.
