### ISSUE TITLE
IDEX requires larger amount of KETH for testing

### ISSUE THREAD

**Issue by bradennapier** [kovan-testnet/faucet#87]
At IDEX Exchange, we continually are running into an issue of not having enough KETH to do proper testing of our exchange.  Being the worlds largest decentralized ethereum exchange we need to do quite a bit of testing and have many team members to coordinate this. 

I can't tell you how much it would be appreciated if we could get an infusion rather than having to fight this all the time!  Thanks for your help on this! 

Can send to our test wallet here `0xf342aaf8e4495fcf8303a9d687449e1267755499` - whatever we can get honestly as we usually end up not being able to test as much as we'd like when we run out of KETH non stop. 

Now it seems yoru gitter channel faucet is broken so we are not sure what to do.

![image](https://user-images.githubusercontent.com/15365418/60148070-7f603700-9784-11e9-97dd-abc08b8e79f0.png)

https://dappradar.com/rankings/protocol/ethereum/category/exchanges

**Comment by ddorgan** [comment]
https://kovan.etherscan.io/tx/0x8949c06dbedb3c8b77e6836ae18adee8dee8c28e366a96c67a22be7a59f5758c
