### ISSUE TITLE
Band protocol require 300 KETH for testing our product

### ISSUE THREAD

**Issue by taobun** [kovan-testnet/faucet#88]
We come from Band Protocol. Now we are developing protocol to feed the real world data to Ethereum network, so we need to report data periodically  (every 10 minutes) for each key of data (eg Price of ETH in 
USD or Sport result). Now we provide about 20 key. After investigating, it consume about 2 ETH per day to send transactions. Therefore for smooth data feed, we don't want to worry about run of ETH to report data.

After estimating gas fee per day, We think `300 KETH` is enough to run our test service. 

And this is link to our smart contract repo: https://github.com/bandprotocol/contracts 

Can send to our reporter address here: `0xB0FF63A87b6395A1E2bae9D92bE1f046c036DC81`

Our product look like this

<img width="1440" alt="Screen Shot 2019-06-28 at 1 37 48 PM" src="https://user-images.githubusercontent.com/26691764/60322573-02aea200-99aa-11e9-9581-10790caad9a3.png">

Thanks for your help!

**Comment by ddorgan** [comment]
Sent: https://kovan.etherscan.io/tx/0xbccb3957bbad491ff80638e8135f734f8180438fb44dab3b85566d6406f88d5e
