### ISSUE TITLE
Request 500 KETH for protocol testing.

### ISSUE THREAD

**Issue by davidqhr** [kovan-testnet/faucet#89]
Hi,

This is david from hydro protocol. The kovan network is fast and reliable. Thanks for the great work. 

Currently we are testing contracts on kovan network. You can see the txs at https://kovan.etherscan.io/address/0x581db8d7c295764635c62d85120ae4903ea74845.

If this request is approved. Please transfer KETH to 0x581db8d7c295764635c62d85120ae4903ea74845 address. Thanks a lot.

**Comment by davidqhr** [comment]
@ddorgan Please review, thanks!

**Comment by ddorgan** [comment]
Sent 100: 0x2c94a23482c8b74f232e2e3f74329027fba820a4059c31711314575c47a0c688
