### ISSUE TITLE
Request 300 KETH for public (and free) Solidity workshop event

### ISSUE THREAD

**Issue by sorawit** [kovan-testnet/faucet#91]
Hi,

We would like to request 300 KETH to use in this public event 
https://www.eventbrite.com/e/blockchain-and-ethereum-smart-contract-101-tickets-66221840307, hosted by the oldest [university](https://en.wikipedia.org/wiki/Chulalongkorn_University) in Thailand. More than 700+ signed up to participate, and we'd love to let them experiment with Ethereum and send a couple of transactions each. However, we don't want everyone to spam on the gitter channel, or other faucets at the same time. We will let students try it in different times so it does not clog the Kovan network.

Please transfer KETH to the following Ethereum address: 
`0x20A0A593382f179FA2542dD622b61b4E0Eab4c87`

Let me know if you have any question, and thanks for you help!

-Sorawit

**Comment by ddorgan** [comment]
200 sent: 0x11aa89a953109f823ebd673474ff17e3ae0904a9b50d231cb2213974135b0adb
