### ISSUE TITLE
Request 500 KETH for Ash beta

### ISSUE THREAD

**Issue by knaub-am-bau** [kovan-testnet/faucet#92]
Like in the alpha we give 1 Keth to every user for setting up the fund and to get some initial assets.
For the beta we expect now more then 800 users to join and for that we need 500 extra Keth.

For more Information you can always reply to me or visit our website https://ash.finance/

Our wallet address is 0x10BaeeFCaeb6dd00F65230DFc0Ba3331d000373A

Thanks for the support.

**Comment by ddorgan** [comment]
200 sent: 0xf629c4aa0e663f53a7e0f9d7c83fe95200ea804c632edd3c852b98829540f990
