### ISSUE TITLE
Github Login for Kovan faucet not working

### ISSUE THREAD

**Issue by Ramarti** [kovan-testnet/faucet#93]
Got a 404 after clicking on login with GitHub

`https://github.com/login/oauth/authorize?client_id=&redirect_uri=&state=<SomeState>&scope=user%3Aemail`

**Comment by laurengarcia** [comment]
Same

**Comment by cheechyuan** [comment]
same problem here

**Comment by MarkusSprunck** [comment]
I have the same problem

**Comment by JohannesMayerConda** [comment]
Confirmed: https://faucet.kovan.network/ "Login with GitHub" button leads to 404 page

**Comment by ddorgan** [comment]
This has been resolved...

**Comment by Delgus** [comment]
Can not login with github. Problem for Firefox

**Comment by Ghostrisen** [comment]
Got a 404 after clicking on login with GitHub
