### ISSUE TITLE
Request 300 KETH for stress testing

### ISSUE THREAD

**Issue by zbroniszewski** [kovan-testnet/faucet#94]
We are stress testing deposits/withdrawals on a cryptocurrency exchange platform at 10 GWEI and 100,000 gas for a maximum of 0.001 KETH/transaction.
Our wallet currently has 4 KETH; enough for a minimum of 4000 transactions of 0 value.
Ideally we'd like to send 100,000 transactions within a short window, replicated for both deposits and withdrawals, which would equate to a maximum of 200 KETH total for fees only. The extra 100 KETH are to be used as value in the transactions and to provide a safe buffer.

Public address: `0x7e2e5Bf5D130da628aF30c38f2844d96A1e5e029`

**Comment by ddorgan** [comment]
200 sent: 0xf2185bb9ff9972035e6e8858c8b7dbff04f82deba47a3ac5743b339f1f0c8848
