### ISSUE TITLE
Request 500 KETH for dapp testing

### ISSUE THREAD

**Issue by pol-hero** [kovan-testnet/faucet#95]
Hello, 
I am a developer at [Raise.it](https://www.raise.it). We are a decentralized loan marketplace and we are going to production in no time, so we will need a bit of KETH to test the different use cases for the different loan types and in different volumes. As we are a few developers I will also send part of these KETH to the other develpers so they can also operate without restrictions.

It would be super helpful if you could transfer around 500 KETH at 0x8bD168BbF95d1a5CEc8D8E6134fc7B05BAA352E7

The project is open sourced at https://gitlab.com/raisehq/contracts-solidity.

Thanks

**Comment by pol-hero** [comment]
Please have a look at our project. We urgently need the KETH.

Thanks so much

**Comment by ddorgan** [comment]
200 sent: 0x6e116e64de3a09bad9eae84153b41445da38fc72cfd892f0a73dd1a392da014f
