### ISSUE TITLE
Request 500 KETH for integration & dex testing

### ISSUE THREAD

**Issue by tshanky** [kovan-testnet/faucet#96]
Leverj.io is the fastest decentralized exchanged that is powered by Gluon Plasma. We have been building and testing all along on Ropsten but need to setup a version and test on Kovan as we are integrating our stack with our #DeFi partners' stacks that have test environments on Kovan. We would much appreciate if we could get this one time bulk Kovan ETH so we are able to rapidly deploy contracts, test algorithmic bots, and integrate via calls to with the partner ecosystem. Sincerely appreciate your help and very grateful for your help. Ideally, a number like 500 would be great but will gladly take any large enough amount for us to test. Please send Kovan ETH to 0xE239Caeb4A6eCe2567fa5307f6b5D95149a5188F

**Comment by tshanky** [comment]
@Tbaut we desperately need some Kovan ETH to test our systems, which is getting ready for launch. Please help.

**Comment by tshanky** [comment]
@Tbaut even if we could get 100 K-ETH for now then that would be very helpful. Sincerely and earnestly appreciate your help.

**Comment by Tbaut** [comment]
I've send you some that I still have, but note that Parity is no longer running nodes on Kovan and therefore no longer get KETH as a validation reward. For that reason please direct your future claims to https://forum.poa.network/c/kovan-testnet

**Comment by tshanky** [comment]
Thanks @Tbaut
