### ISSUE TITLE
100 KETH for testing BitGo API

### ISSUE THREAD

**Issue by supermassive10** [kovan-testnet/faucet#97]
I'm working on a project that intends to create a large number of bitgo eth wallets.  Each of those is a multisign smart contract, rather than a simple address.  We'd really appreciate some test ETH for this project.

0x237b3c1f049b2ad5261900b61587623762ae3562

I've tried the automated faucet on https://faucet.kovan.network.  I sign in with github and I'm prompted for an address.  However when I submit, I see only "Access not verified, please try again" (in red) and nothing is sent.

Thanks for any help!

**Comment by ddorgan** [comment]
sent: 0x1ec7abeeefb079465b50d6fc283400436c4b9d9e2f9717e66c7a0901563e937b
