### ISSUE TITLE
Unable to obtain KETH from faucet.kovan.network – Insufficient Funds

### ISSUE THREAD

**Issue by xpl** [kovan-testnet/faucet#99]
> Internal error: Error: Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 1000049200000000000 and got: 783913292392537902.

<img width="794" alt="Screen Shot 2019-11-24 at 12 35 50" src="https://user-images.githubusercontent.com/1707/69492712-f9712500-0eb6-11ea-9122-1ae3b96bbf9c.png">

**Comment by jcastro-geodb** [comment]
same here

**Comment by maryannxy** [comment]
Same. When I attempted a second time, the error I received was:

`Faucet draw rate limit reached. Come back in 24 hours.`

Kovan Test Network and everything else verified. We've used Kovan for projects in the past.

<img width="363" alt="Screen Shot 2019-12-16 at 5 03 27 PM" src="https://user-images.githubusercontent.com/42249632/70955516-07cddf00-2026-11ea-823e-bd48cd6c945f.png">

**Comment by PierreJeanjacquot** [comment]
Hi,
The faucet wallet is empty:
https://kovan.etherscan.io/address/0x4d6bb4ed029b33cf25d0810b029bd8b1a6bcab7b

Do you plan to refill it?

**Comment by maryannxy** [comment]
I would hazard that it should also be an issue that verifiably failed attempts to get KEth from the faucet result in a 24 hour cooldown. I suggest that failed attempts should automatically reset the timer.

**Comment by windtalker666666** [comment]
> > Internal error: Error: Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 1000049200000000000 and got: 783913292392537902.
> 
> <img alt="Screen Shot 2019-11-24 at 12 35 50" width="794" src="https://user-images.githubusercontent.com/1707/69492712-f9712500-0eb6-11ea-9122-1ae3b96bbf9c.png">

same here , have you handled that?

**Comment by BenBaker21** [comment]
Is there any plan for adding more to the faucet wallet?

**Comment by ddorgan** [comment]
Resolved...
